### ISSUE TITLE
Setup no work 

### ISSUE THREAD

**Issue by om108aman** [tnodir/fort#112]
![Screenshot 2023-07-21 110457](https://github.com/tnodir/fort/assets/10636512/6820fda8-2f85-4476-9549-cc4a40eef0d1)

windows 11 pro workstation 25905.rs_prerelease 230707-1739

also need portable version like simplewall firewall.

**Comment by tnodir** [comment]
See ["Not Compatible with HVCI (Core Isolation)"](https://github.com/tnodir/fort/discussions/108).

> also need portable version like simplewall firewall.

See ["Details of what the various options during installation mean"](https://github.com/tnodir/fort/wiki/User-Guide#details-of-what-the-various-options-during-installation-mean)
