### ISSUE TITLE
HiDPI issues

### ISSUE THREAD

**Issue by pwn0r** [tnodir/fort#113]
First, thanks for this fantastic program, I wanted to try it a while ago but was stuck at 1809 version so could not upgrade. Looks like the most promising opensource windows firewall atm, (almost) surpassing simplewall <3

However the UI does need a lot of fixes and changes. 

For this issue -- i have two monitors, one @ 1080p @ 100%, another 4k @ 200%. Submenus on the 4k monitor often are rendered small, i.e @100% instead of 200%. Then you click again on the same submenu and it shows at 200% as required. A minor cosmetic bug, just annoying to click twice on menu options. 

example, at 200% -- you can see a small submenu and black rectangle filling the correct size bitmap. 

![image](https://github.com/tnodir/fort/assets/19326623/26b86a02-dd8e-4073-8b93-0f544e585b0c)

Windows 21H2; Fort Firewall 3.9.9

**Comment by tnodir** [comment]
> For this issue -- i have two monitors, one @ 1080p @ 100%, another 4k @ 200%.

I've one monitor and I've tried to reproduce the bug as following:
- open Fort's Options window with Scale @100%;
- change Scale to 150%;
- open sub-menu in the Options window.
But it works fine for me.

It seems, the bug occurs when a window moved from one monitor to other with different scale factors...

**Comment by tnodir** [comment]
Ok, I've found 2-nd monitor.

Testing as following:
- open Fort's Options window on 1-st monitor with @100%;
- move the window to 2-nd monitor with @200%;
- open sub-menu in the Options window.

It works fine too.

**Comment by tnodir** [comment]
Ok, I've reproduced the bug:
- open Fort's Options window on 1-st monitor with @100%;
- move the window to 2-nd monitor with @200%;
- close the window and open it again on 2-nd monitor;
- open sub-menu in the Options window.

**Comment by tnodir** [comment]
Depends on [QTBUG-115452](https://bugreports.qt.io/browse/QTBUG-115452).

**Comment by tnodir** [comment]
Fixed in v3.9.12
