### ISSUE TITLE
Regional settings

### ISSUE THREAD

**Issue by pwn0r** [tnodir/fort#114]
For some reason I have timestamps displayed in US format, with AM/PM as well. Windows has a different regional time format configured, and more over, date is additionally configured to match ISO standard i.e. YYYY-MM-DD. 

various apps on the same system display date/time correctly, i.e. 00:00 2023-07-22 etc, like explorer, totalcmd, notepad++ etc. 

This applies both to Programs timestamps and blocked connection timestamps.

**Comment by tnodir** [comment]
Timestamp formatting is due to selected language in the Options.

Let me to add "Use System Regional Settings"  flag to Options..

**Comment by pwn0r** [comment]
yes please. The problem is that the language is EN-US. And normal people in Europe (and plenty of them use their OSes, not just windows) in english rather than translated. And normally people hate this AM/PM notation.  Different language varieties, like EN-UK e.g. use 24hrs notation officially. And DD/MM/YY instead of MM/DD/YY for US. Which is a typical source of confusion. 

Me personally have switched to YYYY-MM-DD (the ISO standard) many years ago, and this one, by the way, has a natural text sort order. The best notation for any table data, either in excel or filelists like in total/double commander or log files.

**Comment by tnodir** [comment]
Implemented in [v3.9.10](https://github.com/tnodir/fort/releases/tag/v3.9.10).
