### ISSUE TITLE
Support SSL decryption

### ISSUE THREAD

**Issue by jmpoep** [tnodir/fort#12]
Support SSL decryption and proxy

**Comment by tnodir** [comment]
Can you please describe use cases?

"proxy" part - I was planning to add ability to proxy programs (as Proxifier do).

"SSL decryption" part - I think, it's out of scope of the firewall and already implemented for example by [1], [2].

[1] https://github.com/mitmproxy/mitmproxy
[2] https://github.com/ghostunnel/ghostunnel

**Comment by jmpoep** [comment]
want to filter the malicious code in the data packet and the advertisement filtering function through the local proxy
