### ISSUE TITLE
FEATURE REQUEST: Save Traffic Graph Window Position

### ISSUE THREAD

**Issue by SPDurkee** [tnodir/fort#120]
I'm writing to request a feature change to the traffic graph window. Currently, whenever I open the window, it reverts to opening in the center of the screen and resetting the size. This forces me to reposition and resize it every time, which is especially time-consuming because I use the window frameless and click-through.

I would like to request that the window location and size be saved so that the window opens in the previous position each time. This would be a great improvement to the usability of the window and would save me a lot of time and hassle.

Thank you for your consideration.

**Comment by tnodir** [comment]
That window should save its position and size already.

What is your environment?
- OS version and build
- which installer did you use: 32- or 64-bit?
- are use using several monitors? Is the window on primary window with main UI?

**Comment by tnodir** [comment]
Are there any errors in the logs?

**Comment by SPDurkee** [comment]
I found the issue. The installation folder was `C:\Program Files\Fort Firewall`, which was preventing write permissions on the INI file. Moving the install to a user writable folder has fixed the issue. I assume this is because I created a portable installation inside `C:\Program Files`, which won't work due to permissions.

You may want to test for this condition during installation and warn the user of portable installations in locations restricted to admin access.
