### ISSUE TITLE
service controls

### ISSUE THREAD

**Issue by pwn0r** [tnodir/fort#121]
This is trivial, however worth registering this as an issue for future reference.

You have a feature there to disable service controls, which for the others would mean disabling windows control on the fort firewall service.  It works and it is good to have it.

However currently you cannot upgrade fort with its installer if this feature is on. Basically fort installer cannot shutdown the service, and user cannot as well. So then you need to close the installer, open fort options, remove the option, then it works. And then you have to reenable this option after upgrade. 

is there a way to properly automate it during installation?

**Comment by tnodir** [comment]
Let me double check it on Monday..

**Comment by tnodir** [comment]
Fixed by b7a48c6d

**Comment by tnodir** [comment]
Fixed in [v3.10.0](https://github.com/tnodir/fort/releases/tag/v3.10.0)

**Comment by pwn0r** [comment]
Just to clarify, this would only work from 3.10 upwards? I.e. when upgrading from 3.10 to a newer version?

**Comment by tnodir** [comment]
Yes, it'll work only when upgrading from 3.10 to a newer version.
