### ISSUE TITLE
UI: Programs: Search doesn't work

### ISSUE THREAD

**Issue by rockenren** [tnodir/fort#127]
Search bar in UI does not return any results for any search queries.
Tried to enter app names/paths manually, then tried via copy name or path from app properties, search doesn't work either.
No errors shown.

Fort Firewall 3.9.12
Windows 10

**Comment by tnodir** [comment]
Can you please send an archived Fort's Profile folder to `nodir.temir@gmail.com`?

The folder is usually `C:\ProgramData\Fort Firewall`, but you can open it by "Profile" button in the "My Fort" window.

**Comment by tnodir** [comment]
Also can you please attach a screenshot of "Programs" window here?

**Comment by rockenren** [comment]
![image](https://github.com/tnodir/fort/assets/11333307/882628d6-d492-4cab-8b39-6fe24fcbf1b9)

**Comment by tnodir** [comment]
It seems like some DB migration bug.. That's why I need to verify the `FortFirewall.config` DB file from profile folder.

**Comment by tnodir** [comment]
@rockenren Thanks for profile's archive. Checking it...

**Comment by tnodir** [comment]
Strange, the `FortFirewall.config` DB does not have a `app_fts*` tables (for full-text search).

Is this a new installation or it was updated from older version?

**Comment by rockenren** [comment]
This is a new installation, never used Fort before.

**Comment by tnodir** [comment]
Ok, let me double check the new installation on virtual machine..

**Comment by SPDurkee** [comment]
Confirmed search doesn't work with an existing installation upgraded to v3.9.12

**Comment by tnodir** [comment]
Fixed by 66910caf.

**Comment by tnodir** [comment]
Fixed in [v3.10.0](https://github.com/tnodir/fort/releases/tag/v3.10.0)
