### ISSUE TITLE
Blocks internet for whole windows

### ISSUE THREAD

**Issue by Tommixoft** [tnodir/fort#13]
Hi, first of all thansk for this app. This is maybe not issue, but app lacks the wiki. I installed it replace windows firewall which i have been disabled in my win10. After installing your app it blocked whole internet for windows. And im able to make windows get internet only when i disable filtering.
Can you please tell me, how should i make FW to work in this maner:
Allows everything but blocks only those apps which is in some blacklist? I did everything but whenver i enabled filtering it made windows to not see internet connection.
Also there is no any alerts when firewall blocks something. Also statistics page do not show any chart/graph.

**Comment by Tommixoft** [comment]
Sorry i may created issue too soon. I wa slooking at settings page instead of main application window...  UI not the best... Dubleclicking on icon should launch main window, not option window IMO :)

**Comment by tnodir** [comment]
> UI not the best... Dubleclicking on icon should launch main window, not option window

Logic is:
- Tray icon’s context menu: Programs, Options, Stats.
- So the mouse’s one click opens the Programs window, double click - Options and middle click - Stats.

> This is maybe not issue, but app lacks the wiki.

Yes, maybe sometime the wiki will be created.
