### ISSUE TITLE
`Kill Process` for Application Groups 

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#133]
Hey @tnodir.
It's been a while 👍amazing Firewall as always.

Title explains it all. I know it is a risk to do it by groups, but I like using Application Groups, since you get enable/disable in tray icon and keyboard shortcuts.

Also for Programs window, is there a quick shortcut to enable and disable Kill process like Allow and Block can be done?

**Comment by tnodir** [comment]
Implemented in [v3.10.2](https://github.com/tnodir/fort/releases/tag/v3.10.2).

**Comment by Emi-Emi-Emi** [comment]
You are the best.

I was like, where is it, but then I found it when I read the important part: _collapsed_.
thank you so much and for all the great implementation, you are the only dev that doesn't make me want to close the Github account. I appreciate your work and listening to feedback and feature requests.

**Comment by tnodir** [comment]
@Emi-Emi-Emi Many thanks for feedback, suggestions and testing.

**Comment by Emi-Emi-Emi** [comment]
Working great, I just have to remember not to click `apply` until I remove it from Programs, the trickiest part lol.

Is there a possibility for wildcard support for Kill Process? for apps that change version names.
For example: `C:\program files\windowsapps\microsoftteams_*_x64__8wekyb3d8bbwe\msteamsupdate.exe`

I already use `C:\program files\windowsapps\microsoft.windowsstore_*_x64__8wekyb3d8bbwe\winstore.app.exe` to allow windows store and other similar WinStore apps.

If too much power can be too risky, maybe a checkbox 'Wildcard support to Kill Process in Application Groups' could be a thing.

But it is a great feature to have so thank you, it was just my usual feedback, request, can be ignored and pretend you never heard it, after testing feature feedback 😁

**Comment by tnodir** [comment]
> Is there a possibility for wildcard support for Kill Process?

Let me try to do it..

**Comment by tnodir** [comment]
> Is there a possibility for wildcard support for Kill Process?

Implemented by ab7ef64b.

**Comment by tnodir** [comment]
As a workaround in current version, you can turn on the "Apply same rules to child processes" flag on any app group.

So, the "wildcard search" will work for all groups with that flag on.

This was an optimization to not use "wildcard search" on every process creation.

**Comment by Emi-Emi-Emi** [comment]
oh, good to know. It wasn't a bad workaround 👍
thanks tnodir! already using it.
