### ISSUE TITLE
Allow to manually update the Path for Programs

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#134]
I have done this is by changing the SQLite DB directly, but would be nice if Paths could be changed directly in the UI, because an app gets updated and then re-added to the Programs lists, which means all the settings attached to it like `apply same rules to child processes` or the `application group` will be set to Main.
So it would be nice if I could just delete the newly added blocked program and just update the old entry with the outdated Path.

Or maybe a way to 'merge' rules, like a way to find duplicated and merge them or something. While it is not the biggest deal, it could be one of those QOL improvements to make things nicer for the user.

**Comment by tnodir** [comment]
Maybe you can use a wildcard path in AppGroup for that changing path?

**Comment by Emi-Emi-Emi** [comment]
I already do that, but I don't do it for programs I don't care about, I guess the problem is how Programs make it nice to for example turn off only "Collect blocked conations" per program, rather than applying to the whole group, or like the child processes one per program which not all allowed programs need, so if sometimes I need to enable an app, I can just go to Programs, A and then B without affecting other programs.
This means I would only have to create a new application group, to block some programs I will never allow, some that I might allow sometimes, and with different individual settings for different scenarios just in case, to make sure nothing gets allowed that shouldn't.

That's why seeing the same app blocked and just removing it, and then double click it and change a version number or because the program changed its name, would be easier.
Just like I do it on the DB, but the problem of DB is how I have to close Fort and sometimes restart the whole service for changes to apply, unless this is the issue, like something like that and it is 'too much work' I guess I grew up lazy about it lol.

In that case, let's change the request, to maybe a add a setting to hide specific groups from showing in the tray icon? so I can create 800 groups if I want but only have 5 that I need accessed when I right click the tray icon or use shortcuts (is there even a limit?). 

I like using Application Groups more than Applications, but I still see the need for Programs in some cases, like how easier is to access Programs than Application Groups if needed. Like I don't even know if you can open specific tabs from Options instead of just Options to make it easier to access Application Groups easier, or with a click in the tray icon or some shortcut too, to edit the Application Groups, like it is done with Programs.

This is why I requested the Kill processes for groups, so I can transition more to using Groups rather than Programs, which is nice and useful but I like the power of Groups. I want all Programs features in Application Groups, even the _Agnitum Outpost_ type of rules if needed, and if that's the case, creating more groups would be needed, so I think being able to choose which ones show in Tray Icon would be a better request now I think about it then, that would make a more useful request for sure to use more Groups and less _Programs_.

**Comment by Emi-Emi-Emi** [comment]
oops, guess my comment is accidentally gone, hit the wrong button lol but I still hope you got it.

**Comment by Emi-Emi-Emi** [comment]
Oh it's good to know the exact number, thanks.
I have only used 10 groups, but removed some to make the tray icon less cluttered and easier to find the groups I needed the most. Still 800, sounded like a good number, and a good dream to have 👍

**Comment by Emi-Emi-Emi** [comment]
I will close this in favor of the new FR, just because the other one is useful and this Application Groups need some love, because they are more useful.
Plus paths needed to be unique and all, can cause issues? maybe not, but I guess it's better to suggest real improvement for what has to be improved and not unnecessary FR, I can edit the DB if needed, while I can't do anything about AppGroups in tray icon unless I remove the groups.👍
