### ISSUE TITLE
`IP addresses` Include All / Exclude All not working properly. 

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#136]
Steps to reproduce:
1. Go to IP Addresses
2. Uncheck `Include All`
3. Hit Apply
4. Switch to another tab
5. go back to IP addresses
6. `Include All` is still checked.

If we check the SQLite DB, you can see how the DB never gets updated to the 1 or 0 value.

If you manually change the option, and restart the Fort service, it will function properly. like if you Include all in Internet Addresses and Exclude all in Allowed Internet Addresses it should stop allowing all IPs.
That means setting the `address_group` to:
```
1	0	1	0	0	0		
2	1	0	1	0	0		
```
And restarting the service should work as expected, so the problem is the UI is not updating DB, not the feature itself.

**Comment by tnodir** [comment]
Fixed by 392795f5.

Note that the final logic is [here](https://github.com/tnodir/fort/blob/392795f5590345984dc80987541854c8e9e4fd6c/src/driver/common/fortconf.c#L184).

**Comment by tnodir** [comment]
Fixed in [v3.10.2](https://github.com/tnodir/fort/releases/tag/v3.10.2).
