### ISSUE TITLE
Fort prevents PC from entering sleep (Windows 10)

### ISSUE THREAD

**Issue by YZgitter** [tnodir/fort#137]
It prevents automatic sleep based on inactivity. The screen turns off, but the PC doesn't enter sleep.

I noticed the same problem on two different PCs, so it's probably not specific to any config. But I didn't see this problem on Windows 11.

**Comment by tnodir** [comment]
Also you can view programs list, which prevent sleeping by the `powercfg -requests` command (run it as Admin).

**Comment by tnodir** [comment]
Let me check Win 10 on VM..

**Comment by tnodir** [comment]
Fixed by e5a52a36.

**Comment by tnodir** [comment]
Fixed in [v3.10.2](https://github.com/tnodir/fort/releases/tag/v3.10.2).
