### ISSUE TITLE
Allow to hide Application Groups from tray icon's menu.

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#138]
Application Groups are great, so one improvement would be to be able to create them, but don't have them in the tray icon if their only purpose is to be always disabled or enabled and never change, but take advantage of wildcards and everything Application Groups offer, only the ones that matter would be in the menu, improving Application groups to be able to be more used, without cluttering the My Fort / Tray icon's menu.

Based on the conversation we had here https://github.com/tnodir/fort/issues/134

**Comment by tnodir** [comment]
Implemented in [v3.10.2](https://github.com/tnodir/fort/releases/tag/v3.10.2).

**Comment by Emi-Emi-Emi** [comment]
I noticed that hidden AppGroups from tray icon, get disabled when you enable or disable any 'shown' AppGroup from tray icon, so if you have 10 groups, and you only show 1, and you enable or disable that 1, all other 9 should be disabled.

This only happens to new groups, and the ones that didn't 'enter' the count number when created.

1. Set the count to 1
2. create groups
3. disable the Main from tray icon or My fort menu, all the others get disabled.

Then:
4. Set count higher and click Apply
5. set count to 1
6. disable and enable Main, the AppGroups don't get disabled.

7. create a new group
8. disable Main
9. now the new group gets disabled but not the others.

**Comment by tnodir** [comment]
Thanks, fixed by 81d04c1e.

**Comment by tnodir** [comment]
Fixed int [v3.10.3](https://github.com/tnodir/fort/releases/tag/v3.10.3).
