### ISSUE TITLE
Apply same rules to child processes doesn't seem to work?

### ISSUE THREAD

**Issue by HGhostRevisionist88** [tnodir/fort#14]
Hi,
I am testing new feature and it seems like it doesn't do what I thought it would do.
I have used **Apply same rules to child processes** in Tinywall and I don't know if it is suppose to work exactly like it, like if you took the idea from it, but testing it it doesn't seem to do anything at all in my tests, so I don't know what it is suppose to do.

I first used Brave - Tor windows, when you open a Tor window it is a child process of Brave, opened Brave program's rule and checked the box Apply same rules to child processes, but when I opened Tor, Tor was added as blocked (alert) to the Programs window and shows as blocked in Blocked Connections.

I also used MPV - yt-dlp/youtube-dl, when you load a twitch stream or whatever, yt-dlp becomes a child process to get the URL so Mpv can play it. well, same happened, yt-dlp got blocked and it seems like nothing got applied to the mpv child processes.

I still don't know how it works, the logic you built for it, like if is it suppose to be automatic regardless of being blocked or allowed in Programs lists? like if yt-dlp is blocked, but mpv has the Apply same rules to child processes flag to it, will it be allowed or blocked? the correct thing would be to be allowed regardless of it being blocked in program lists, or that's how I think it should be. That's why I ask that as well.
Like in my mind, for example, it should work like this: yt-dlp is not in the Programs list, so it is not allowed or blocked, but if mpv is blocked with Apply same rules to child processes, then it will block yt-dlp but without adding anything to Programs list, and then if other program gets allowed with Apply same rules to child processes, like Foobar, then it can use yt-dlp. And if an app doesn't have Apply same rules to child processes flag on it tries to use yt-dlp, then it gets blocked but doesn't affect Foobar since it has Apply same rules to child processes in it. 

is that how it is suppose to work? or am I thinking way too much?

Anyway, I even tested adding Brave browser to App Groups and allowing the same rules to child process there, but same result, it gets blocked and added to programs window and nothing can seem to happen, since program lists override anything.

Just wondering, asking and maybe report the bug. 

Have a nice day.

**Comment by tnodir** [comment]
Hi, thanks for testing this new feature.

Yes, the idea is from Tinywall.
But with BIG Restriction: The option affects only new processes.

So, you described exactly correct logic of  how it should work. But again, you’ve to restart the program to take effect.

Please let me know, if it doesn’t work for new processes.

**Comment by HGhostRevisionist88** [comment]
Yeah I knew it, I loved that feature from Tinywall, it's nice you implemented it!

Yes, I restarted programs like 100 times, even tried with a complete new ProgramData folder, but also, deleted and re-added programs from list and groups many times, made new app groups with the apps, stopped service and started it, stopped service and driver, opened fort as admin, even reinstalled driver, also turned on and off Collect new blocked programs to make it easier for the process not to get added as blocked, but to see if that changed anything.

Tried other programs like SyncTrayzor, which i am sure opens syncthing as a child process.

I even restarted computer in case some weird bug was the reason and nothing.

I am using win11 btw.

Also, how does Fort detects the child process? like When I see task manager I can see for example mpv, and ytdlp and ffmpeg fine. But Task Manager sucks at displaying the real process tree, Process Hacker/Explorer shows the real list, like when you open programs through Flow Launcher or Powertoys run, it will open programs as a child process under it, if you use a shortcut or a folder it will do it under explorer.exe, if you use processhacker run or nirsoft advancedrun it will also become parent, etc etc.
I was even using wmic to really see the child and parent process in cmd, so will Fort detect it like that or it is more like the way task manager does it? I think I already answered my question, but I tested with Flow launcher and mpvnet and SyncTrayzor and Brave, and advancedrun because ProcessHacker, even opened and closed like Windows Terminal so mpv as a child process would become parent, in case that was the issue and nothing, but probably tried unnecessary stuff.

I think I tried everything but I think I was overthinking it so much as well, trying everything possible to see if it would work like when I allowed Brave in Tinywall and then Tor worked perfectly without problems.

**Comment by tnodir** [comment]
Let me check it with mpv.

I use ProcessHacker2 to see process tree.

Actually I've tested the feature as following:
- set "Apply same rules to child processes" to "C:\Windows\Explorer.exe"
- logged out/in to restart the "Explorer.exe"
- turned off Fort's "Start as a service"
- launched Fort (as child of "Explorer.exe")
- checked for new version in the Fort's Options -> Schedule tab
- it worked fine.

**Comment by HGhostRevisionist88** [comment]
So I understand the problem now with your Fort/Explorer.exe test.

Fort in your case is like the only child process for Explorer.exe.

The problem is when there is more than just one, for example, I allowed Flow Launcher with Apply same rules to child processes, and when I open mpvnet and load m3u8 channels, it works since it doesn't require yt-dlp (or the symlink I created named youtube-dl). When I load a Twitch channel which requires yt-dlp, then the tree will have yt-dlp.exe and then 2 child process conhost.exe and yt-dlp.exe and then it fails.

Brave's Tor has the same problem, Brave.exe is the parent, then many child process Brave.exe and then Tor is child process of one of those child processes.

Since I allowed Flow, anything that gets opened through there should work too. so, I opened Process Hacker 3 as admin (if not it doesn't open as Flow child) and I checked updates and found an update, updated and when it restarted, then it didn't have connection since it wasn't child process anymore.
Blocked PH in Programs list and when I opened with flow, it still could check updates, so it works like it is suppose to work.

But it seems Fort is not checking the whole tree of of child processes, because anything that is a child process of the child process doesn't get connection. Visual Code has the same, since it opens a big tree of Code, then like 6 Code.exe child process then other 2 child process under one of those child process, then nothing.
Removed Brave from the Programs lists, opened with Flow and same problem, because it has so many child processes under the already child process that one doesn't get the internet connection to work, the only one that gets it is the direct child process and nothing else.

**Comment by tnodir** [comment]
Mpv is crashing for me. Let me check Brave browser...

**Comment by tnodir** [comment]
> But it seems Fort is not checking the whole tree of of child processes, because anything that is a child process of the child process doesn't get connection.

Fort checks the whole tree of child processes at first attempt of any (child) process to connect.

I've tested the Brave browser with private Tor window:
- installed portable Brave
- added Brave.exe to Programs with "Apply .. to child .."
- opened private Tor window
- it works fine

**Comment by tnodir** [comment]
What is a "Flow"?

**Comment by tnodir** [comment]
I've re-checked the Brave browser now and it doesn't work. Investigating...

**Comment by HGhostRevisionist88** [comment]
Flow is a Launcher like PowerToys Run, so almost anything should become a child process when launching from those launchers.
Allowing Flow Launcher with child process rule, made it easy to test mpv and process hacker, so I saw it working for some part, but with anything with more than 1 child process buried inside other child process seems like no, like with Skype, Code.

The best test was with mpv since you can use it both ways and one worked fine when dropping m3u8 links but once I dropped a twitch link with the same instance of mpv, it failed.

**Comment by tnodir** [comment]
> The best test was with mpv

How can I install it properly?

**Comment by tnodir** [comment]
Ok, I found a bug with nested processes more than one.
I'll create v3.5.1-RC0 for testing later today.

**Comment by HGhostRevisionist88** [comment]
https://github.com/stax76/mpv.net/releases/download/5.4.9.0/mpv.net-5.4.9.0-portable.zip

Download and put https://github.com/yt-dlp/yt-dlp/releases/download/2022.02.04/yt-dlp.exe anywhere and add it to PATH so mpv.net finds yt-dlp easily.

then get any twitch URL and press u (which opens the URL from clipboard), it should try to load yt-dlp and for m3u radio links I found this website that can be useful https://www.wxxi.org/listen/m3u

**Comment by tnodir** [comment]
Please test v3.5.1

**Comment by HGhostRevisionist88** [comment]
It works great now!
I found a little miss-behavior though which might be another reason why I was having so much problems getting it to work in the beginning, I even went ahead and did the extreme case of setting Windows Terminal as allowed and applied same rule for child process and it worked in the end.

The problem is simple:

If you manually add a program to Fort Programs list, and you enable **Apply same rules to child processes** the program doesn't get connection, I am not talking about child process but the program itself doesn't get connection, even when you restart it. the only way to fix it is to restart Fort Service.

The way to do it so Fort doesn't have to be restart is to add the program without Child Processes flag, normal like before, just ignore it and click ok, the program gets connection just like it is suppose to do. Now, Edit the rule and enable the Child Processes flag, you get normal internet connection and when you restart the program like Fort needs, all child processes will get allowed, without restarting the service.

The problem is manually adding the program directly with flag on. If I had "collect new blocked programs" enabled then it will do the adding automatically and editing should be enough, but not if I disable it and decide to do everything myself because I don't need all blocked apps in my list.

**Comment by tnodir** [comment]
> If you manually add a program to Fort Programs list, and you enable Apply same rules to child processes the program doesn't get connection

There is another bug.
Thanks!

**Comment by tnodir** [comment]
Fixed in [v3.5.2](https://github.com/tnodir/fort/releases/tag/v3.5.2). Please test.

**Comment by tnodir** [comment]
I'm checking the "Windows Time Service" (\svchost\w32time):
- stopped the service
- added "\svchost\w32time" to Programs, checked on "Child Process" and Allowed
- opened "Internet Time Settings" dialog and clocked "Update now"
- it works as expected.

**Comment by tnodir** [comment]
Also tested the Brave browser:
- added to Programs with "Child Process" and Allowed
- started the Brave - it opens sites and Tor window works too

**Comment by tnodir** [comment]
@HGhostRevisionist88 Can you please describe step by step how to reproduce the issue?
Which program to run and etc.

**Comment by HGhostRevisionist88** [comment]
It works perfect now!
I took a screenshot and added the colors for how I tested it with Process Hacker

RED = when mpvnet wasn't allowed
Yellow = When I added program to Fort
Green = When I restarted mpvnet and then Child process (yt-dlp) worked too.
![works!](https://user-images.githubusercontent.com/44932435/155168577-57c43e19-ef0b-40de-b146-adabf06b858c.png)

I tested Program Groups and Use Application Group's Enabled State and no problems disabling and enabling the setting and all that stuff. it worked as expected, everything was allowed perfectly fine.


---

I found bugs unrelated to this issue though so you can test it and fix it eventually. It is about Application groups, because when I was testing I encountered it and it was confusing but then I remembered I had these problems before with App Groups so it was easy to deal with it.

First Bug:
Create an Application Group and click Apply (don't close window). Enable option settings, like Apply same rules to child processes  and apply it, download speed limit and apply etc.

Now go to the tray icon and see how many groups named the same. If you restart options window, then you will see the different tabs and how the options matches when you were hitting Apply.
Also, the groups that get created after are disabled so when you restart the app to get the Child Processes allowed, you will get like no connection because apparently the disabled groups will override the enabled one.

Second Bug:
Also there is another bug. create a group, name it whatever, hit apply, restart the options window. Delete the group and hit apply, now create a new group and then the group doesn't get created. If you create a second one, then it gets created. but not the one after deleting a group.

Third bug: it can be the simple one, create a group, delete it and it will still be created and will appear again when you open the Options window.

I am sorry to put more work in your shoulders but thought I would report those bugs. I easily replicated the issues in another computer where I don't manually modify anything about Fort databases, and just created normal rules and never organize or delete anything inside the databased like how I use foreign keys in stats DB to easily edit it. So I made sure is not just my computer.

Thanks for your work and hope you have a good day!

**Comment by tnodir** [comment]
Many thanks!

**Comment by HGhostRevisionist88** [comment]
I will make sure to test it! I like the nature and features of App Groups more than the Programs list, so I use them but it was complicated to create them because making them was a hit and miss and sometimes restarting option windows 3 times or more, I always forgot to report the bugs but it is nice if it gets easier to use them.

`Which foreign keys do you use?`
Yeah, I found using foreign keys was my solution to manually edit the traffic stats DB easily. The problem I was having is how if I use Enabling the Blocked Connections, they get added in the same app table as the traffic apps and I needed a faster way to delete or edit/change the ids of the programs without me using SQL syntax and making it more complicated. 


So the foreign keys is just me being a wierdo and wanting things to be editable easy and keep things in order.
Especially because I don't use Blocked Connections often, since Process Hacker 3 nightly has the Firewall tab, and PH3 has the advantage of displaying Allowed connections, filter the apps so I only see what I want to see and it doesn't write to disk like the Fort would do to the DB, and well, it doesn't modify the DB so it keeps it cleaner, but I notice that Fort would write too much to disk which I mean, I don't care but writing to disk still affects its lifespan (but I don't worry much about it).

I used Blocked connections a lot with new svchost filtering to see the non-identified svchost blocked by their PID and then make it trackable so it would get filtered by Fort and take advantage of that amazing feature.

But Windows store apps use different path for each version, so if the app got allowed it will create new stats for the new path, so I needed a faster way to delete the newly added app, with foreign keys, then then all the data will be removed from the hour, month etc stats automatically, and then I only had to update the old app with the new path so it keeps using the same stats.

It would be nice if paths could be updated on the UI, in program lists and Traffic stats, or maybe some merge or something if two programs have the same .exe, but I got used to editing the DB.

That's the story why I added the foreign keys. But I doubt they will be much useful for anything. To answer your question
I dount anyone really edits the DB, but it is better than using the SQL query.

Thank you very much for your Firewall! Take care 👍

**Comment by tnodir** [comment]
> I will make sure to test it!

Please check [v3.5.4](https://github.com/tnodir/fort/releases/tag/v3.5.4)

**Comment by HGhostRevisionist88** [comment]
I got the same issues about creating application groups.

If I create an empty group and hit apply, add a path and apply, and all the other options and apply. Get multiple groups, and only first one enabled.

If I restart options and delete all those groups, then if I create groups, they won't appear. so Options has to be restarted after groups deletion in order to add groups after deleted a group.

And if I create a group apply and delete it, it doesn't get deleted.

![Bug](https://user-images.githubusercontent.com/44932435/155506757-64064428-fe8c-4789-91d9-6835003d9065.png)

**Comment by HGhostRevisionist88** [comment]
It is working great.
Tested adding, deleting, adding many groups, renaming, applying different options and nothing produced a problem. Checked DB and saw it updating without problems as soon as I hit apply.

Thanks!
