### ISSUE TITLE
Small visual bug with Groups and the sample 'examples' text from empty  allow columns

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#145]
![image](https://github.com/tnodir/fort/assets/152097351/f8b06cab-023f-4742-bb36-d8da20a8d678)

I noticed this issue when you switch between Groups.
The sample text gets inherited from other groups that only have blocked or kill processes rules, and it only happens if there is 1 or 2 lines of text in the Allow column with no enter between them. 

So if it is like this, it will work fine:
```
# Example

**\test.exe
```

But not this one:
![image](https://github.com/tnodir/fort/assets/152097351/c8e6dc7d-e064-49ff-8927-a2fa5c105105)

I also notices that a long path that warps warps, will not show the issue, even if it is still 1 line showing as 2.

It is just a visual bug, the functionality in Fort groups is great 👍 and the best solution is just to hit enter in any new group's allow column just to make sure it stays blank but doesn't show the sample text = no issues when switching to other groups.

**Comment by tnodir** [comment]
It looks like a bug in Qt. Let me double check..

**Comment by Emi-Emi-Emi** [comment]
Oh, so it is upstream? well, hope they fix it soon then!

**Comment by tnodir** [comment]
Depends on [QTBUG-119808](https://bugreports.qt.io/browse/QTBUG-119808).

**Comment by tnodir** [comment]
Please check the [v3.10.5-test0](https://github.com/tnodir/fort/releases/tag/v3.10.5-test0).

**Comment by Emi-Emi-Emi** [comment]
LGTM
