### ISSUE TITLE
Fort Firewall for Winget

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#148]
I don't know how easy is to add or maintain the Winget packages to https://github.com/microsoft/winget-pkgs

Apparently they say it can be easily created and updated with: https://github.com/microsoft/winget-create.

But it would be nice if we could just go to terminal and add `winget install fort.firewall` and done, or well, update it it with `upgrade`. 

~~The only requirement would be Fort Firewall has to have a silent installation mode in place so it can be used in Winget with it.~~

~~There is a issue opened to allow _non-silent installations_, in case, but it has been there for a while https://github.com/microsoft/winget-cli/issues/910 with no signs of life and won't happen until who knows when.~~

Winget is preinstalled in all Win11, so this makes it a good thing for tech experts, but even for people who are not tech savvy, so it is easier for them to install Fort without too complicated steps, just terminal, run command and done.

**Comment by tnodir** [comment]
Fort's installer already supports `/SILENT` argument (due InnoSetup).

**Comment by Emi-Emi-Emi** [comment]
Oh nice. I didn't know if it did or not, I guess my post sounded like Fort didn't but I meant a requirement was the silent installation, if not waiting for them to fix that issue which would allow more programs to be in Winget. 👍

**Comment by Emi-Emi-Emi** [comment]
Well, I tried to do it and add Fort to winget, but didn't work for me. I found out about https://github.com/russellbanks/Komac so I was more interested about it, because it gets the release notes which is cool and has a long description to write about the features Fort offers, so I even added a nice long description with Fort features. but didn't work, because couldn't create the branch or whatever. I don't know about Github stuff and CMD stuff.

The only thing is Komac doesn't recognize the installation as inno though, like winget-create does, but I just selected exe and added /SILENT to both questions and done, I didn't want to write an issue to Komac and ask why.

There is a https://github.com/marketplace/actions/winget-releaser BTW if you are ever interested, which would automate everything so the new releases get uploaded automatically.

I guess, using cURL to download fort, and then run the installation remotely or with SSH or physically with the /SILENT is way easier and it is pretty much the same without headaches of all the Github stuff.
Now I wonder why would anyone waste their time trying to upload the programs to winget lol.

Silent is the only/most important part apparently for it to work fine, so I will close the issue. I don't think winget has anything to complain about Fort, since it installs fine with /silent

**Comment by Emi-Emi-Emi** [comment]
Ok. I have made progress about this, it's been time consuming and messy, but I am getting somewhere and it should be in Winget packages repository soon.

With the tests I was making I found an issue with the installer, which applies to everyone.

Since Winget has to be a silent installation, it also has the 'dependencies' to install dependencies first before the installer, which is great.

Now the problem is https://github.com/tnodir/fort/blob/af6218419e4fe9c75b6a0b32f232ee62b3e4e99e/deploy/FortFirewall.iss#L94 is only checking for VCRedistx86, so when I install `Microsoft.VCRedist.2015+.x64`, it still only checks for the x86 version, it will not throw and error of 'not finding the dll' but still opens the browser and the website to download the latest one.

I guess this shouldn't happen in x86 since it is getting installed by the dependency, but I guess ARM should have the same issue.

This is why I was getting an error in dependencies, I thought Microsoft.VCRedist.2015+.x86 was the needed package and it was throwing the dll error, but doing the winget sandbox test, I could see how the MS website opens even after it installed correctly.

Apparently, while winget doesn't like scripts, there is no issues installing the driver, or there is no issues with the driver throwing the memory integrity/core isolation problem. I still added to the Description the warning, even if you also display the warning in the installer.

But this is one problem I found doing tests, not a big problem, but it should be detected per architecture/platform, so doesn't open the browser even if it works fine.

**Comment by tnodir** [comment]
I think, we can skip the VCRedistx86 check in silent mode..

**Comment by tnodir** [comment]
> I think, we can skip the VCRedistx86 check in silent mode..

Fixed in 8c98e1cd.

**Comment by tnodir** [comment]
> But this is one problem I found doing tests

Fixed by b15d80f1.

**Comment by tnodir** [comment]
Please check the [v3.10.5-test0](https://github.com/tnodir/fort/releases/tag/v3.10.5-test0).

**Comment by Emi-Emi-Emi** [comment]
Tested x64 on both interactive and silent and manifest installed with no issues in Sandbox. 👍

**Comment by Emi-Emi-Emi** [comment]
BTW, the only thing I saw is that installer has 'Launch Fort Firewall' checked on interactive, but in silent the program doesn't open after being installed. But not an issue.

**Comment by tnodir** [comment]
@Emi-Emi-Emi Thank you for your feedback! Marry Christmas and best wishes for 2024!

**Comment by tnodir** [comment]
> the only thing I saw is that installer has 'Launch Fort Firewall' checked on interactive, but in silent the program doesn't open after being installed.

It's because of `skipifsilent` flag. We can add cmd line argument to run it, if needed.

**Comment by Emi-Emi-Emi** [comment]
It could be added if you want, but it is not needed for Winget. 

But for example, since I add FortFirewall to PATH, then I can just type FortFirewall after using winget, or do what I already do, `start /wait FortFirewall-3.10.5-test1-windows10-x86_64.exe /silent && FortFirewall.exe` and done, plus I use Powertoys Run so it is fast, but there is Start Menu for the normal people, so there is no issue about opening Fort after silently install it, so it would be just more convenient to open it automatically, just as interactive has the option.
If anything, Winget manifest can also have custom arguments for the installer too.

**Comment by Emi-Emi-Emi** [comment]
Finally it passed the checks 👍No issues with scripts, driver or anything. https://github.com/microsoft/winget-pkgs/pull/132381

The reason it didn't pass before in my last two tries was for dependencies and then because of a space I missed for the YAML format to work, although it didn't throw any error in my side, it did on the Azure pipeline, I figured it could be that and fixed it, but waited until today to make the PR for the newer version.
