### ISSUE TITLE
Block Scheduled in Program list small issue.

### ISSUE THREAD

**Issue by HGhostRevisionist88** [tnodir/fort#15]
Hi,

When you use schedule either by using Block in or Block at, the Program's name changes to a 0 or 1, when the program gets blocked.

There also seems to be a weird issue with **Block At** not respecting the time scheduled for the block. I wanted the program to be allowed for some minutes and not 1 hour, so I used Block At.

It seems 5 minutes is the minimum that will be scheduled, so if you clock says 10:00 you can't set it to 10:02 or anything less than 10:05 because it would get ignored.
But the issue I found is mostly how I created many schedules and all of them got blocked at once at 10:15, because I kept editing programs and adding new schedules and then it was like the time was getting reset to 5 minutes, so the last rule I added was at 10:10, set to block at 10:13 and then it worked until 10:15, but then all the other 10 programs I was set to block at 10:02, 03, 05, 06, 07, and 09 and 10, didn't work because they inherited the 5 minutes from the last scheduled added. 

But I made  a second test at 10:45, the schedules were set to be blocked at 10:50:37, 10:52:37 and 10:55:37 (I checked the seconds on this second test) the first rule got blocked some seconds after 10:50:37, but the 10:52:37 didn't get blocked properly, it was blocked at 10:56 when the last schedule was blocked so the 3 minutes difference was totally ignored by Fort.

I mean, not like it matters much since the difference is minimal and it is something nobody would notice or care but I thought I would mention it since it is suppose to be blocked by the clock time, not like seconds or minutes after a rule was created like Blocked In, does. And even if that was the case and it wants to use 5 minutes increments, a schedule shouldn't affect the others, so the one that was set to be blocked at 10:02, shouldn't be affected by the one at 10:10. So it is technically not working as expected even if it is insignificant issue.

The real issue here is the program name getting replaced since programs have to be opened one by one to get the name again.

**Comment by tnodir** [comment]
Thanks, fixed in [v3.5.5](https://github.com/tnodir/fort/releases/tag/v3.5.5).
Please check.

**Comment by HGhostRevisionist88** [comment]
Oh, that was quick! I tested with many programs at different times and seems to work prefect now.
Thanks!
