### ISSUE TITLE
poor text rendering at 16-bit color depth

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#151]
1. Set 16-bit color depth in OS
2. Try to exit Fort
3. See result

![16bit](https://github.com/tnodir/fort/assets/11581901/5210c54e-ec64-4204-9de7-2b05739e9e35)

Environment:
virtual box
windows 7 x86 (guest os)
16-bit color depth (in OS)

**Comment by tnodir** [comment]
@b-user What screen resolution do you have?
