### ISSUE TITLE
line endings for *.cmd ; *.bat

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#156]
It is almost impossible to edit [install.bat](https://github.com/tnodir/fort/blob/master/src/driver/scripts/install.bat) (etc. , for example *.cmd) in Windows 7 (using notepad) 

Please normalize line endings (crlf ; \r\n) for *.cmd ; *.bat
I guess this can be done using .gitattributes or something similar
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by tnodir** [comment]
Fixed by c5c7c546

**Comment by tnodir** [comment]
> Not for all files, only for *.cmd; *.bat

What do you mean?

Можно на русском писать.

Я поправил `driver/scripts/*.bat`. Надо было что-то другое?
