### ISSUE TITLE
automatic localization, according to the locale

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#157]
In the settings menu I can select localization.
Could you please add the item "automatically, according to the locale".

**Comment by tnodir** [comment]
Fixed by a12c5da7.

**Comment by tnodir** [comment]
Please check [v3.10.5-test1](https://github.com/tnodir/fort/releases/tag/v3.10.5-test1).

**Comment by tnodir** [comment]
Fixed in [v3.10.5-test2](https://github.com/tnodir/fort/releases/tag/v3.10.5-test2) to use actual System Language, not System Locale's Language.

**Comment by tnodir** [comment]
> как простым способом удостовериться что запущенный fort это v3.10.5-test2 ?

Сейчас никак из-за лени)
А надо бы добавить индикатор тестовой сборки в версию..

**Comment by tnodir** [comment]
Странно, этот кейс у меня работает:
![fort-syslang](https://github.com/tnodir/fort/assets/303655/0d5e151e-02ec-4aba-8bea-39409bfd9d42)

**Comment by tnodir** [comment]
Дистриб русский вроде: `Windows 7 SP1 52in1 (x86-x64) +- Office 2019 by Eagle123 (07.2023).iso`.

**Comment by tnodir** [comment]
Может всё-таки старая версия?

**Comment by tnodir** [comment]
> я говорю "если в проге есть автодетект языка", то создавать в ярлыке --lang=xxx - вредно"

точно. тоже думал, что надо убрать..

**Comment by tnodir** [comment]
Итак.
При смене языка на English, Винда делает логофф.
После логина Форт должен показать всё на Англ-ком, т.к. выбран Системный язык.
Сейчас перепроверю..

**Comment by tnodir** [comment]
> странно. с итальянским - всё нормально.

Логика обработки системного языка такая:
- при установке локалей для поддерживаемых языков сравниваем имя локали на англ-ом с системным языком
- если находим локаль для сист. языка, то UI может его использовать для перевода

Значит для англ-го имя отличается что-ли..

**Comment by tnodir** [comment]
`English`

**Comment by tnodir** [comment]
> HKCU\Control Panel\Desktop\PreferredUILanguages

Что у вас там содержится?

**Comment by tnodir** [comment]
> HKCU\Control Panel\Desktop\PreferredUILanguages

Лучше из реестра брать?

Сейчас так:
https://github.com/tnodir/fort/blob/ef30b5f7a066ad5d67fd7ba48cef0121f2263eff/src/ui/util/osutil.cpp#L125

**Comment by tnodir** [comment]
Лучше из реестра получить `HKCU\Control Panel\Desktop\PreferredUILanguages`.
Т.к. именно такой формат мне и нужен.

**Comment by tnodir** [comment]
Ашчув ин 8aec6951ю

**Comment by tnodir** [comment]
> я говорю "если в fort есть автодетект языка, то создавать в ярлыке --lang=xxx - вредно"

А если в системе стоит English, но в Установщике выбираю Russian?
Пусть остаётся этот параметр. Не мешает же?

**Comment by tnodir** [comment]
Please check [v3.10.5-test3](https://github.com/tnodir/fort/releases/tag/v3.10.5-test3).
