### ISSUE TITLE
missing vcredist x86 

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#158]
When trying to install FortFirewall-3.10.5-test0-windows-x86.exe in Windows 7 (presumably when vcredist 2015 is not installed in Windows), a browser opens with a page https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

It is unclear what exactly to download (there is more than one link on the page, and in a language I do not understand - English).

For FortFirewall-3.10.5-test0-windows-x86.exe / x86 would be more logical (in my opinion) to open https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by tnodir** [comment]
Fixed by 58041855
