### ISSUE TITLE
SHA-2 code signing support update for Windows 7 and Windows Server 2008 R2

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#159]
When I try to install FortFirewall-3.10.5-test0-windows-x86.exe on Windows 7 (in case Windows does not have "sha2/sha256 signature support"; when the driver file signature is invalid), the message "This program is not compatible with Windows 7 (KB4474419 required)."

I don't understand:
a. What does it mean
b. where to get KB4474419

Perhaps this means:
A. https://support.microsoft.com/help/4474419 (they write something here. But it’s not clear why I should read this. I’m more interested in what to do in such a situation.)
B. https://www.catalog.update.microsoft.com/Search.aspx?q=KB4474419 (again, it’s not clear which one)

Perhaps a better option would be:
*. clearer "install this and install that" instructions
*. It’s even better to install it automatically: now this and that will be installed + warning about reboot/need to reboot.

**Comment by tnodir** [comment]
I would say that it is not Fort's problem to find how to install the KB4474419 :-D

> B. https://www.catalog.update.microsoft.com/Search.aspx?q=KB4474419 (again, it’s not clear which one)

If it is a Windows 7 32-bit version, then this: `2019-09 Security Update for Windows 7 for x86-based Systems (KB4474419) `.
For Windows 7 64-bit version: `2019-09 Security Update for Windows 7 for x64-based Systems (KB4474419)`.

We can add a note to [FAQ](https://github.com/tnodir/fort/wiki/FAQ#windows-7-sp1-64-bit-fails-to-install-drivers-that-are-not-digitally-signed).

**Comment by tnodir** [comment]
Let's just open browser with the `https://www.catalog.update.microsoft.com/Search.aspx?q=KB4474419` link?

Added in d5b849aa.
