### ISSUE TITLE
driver installation message window

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#160]
While installing the driver, a console window appears for a split second with the message “End execution... Error” something like that.
I see an "error" message and it scares me.

@echo End execution... Error Code = %RCODE%
https://github.com/tnodir/fort/blob/master/src/driver/scripts/install.bat#L52C15-L52C15

Please change the wording so that the message does not contain the word "error".

**Comment by tnodir** [comment]
Fixed by c5c7c546
