### ISSUE TITLE
 button geometry (slight visual defect)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#164]
(small visual defect)

options - options - statistics (tab)
![stat-button](https://github.com/tnodir/fort/assets/11581901/bd357996-2ca1-42ee-99ff-0a63551893c9)

**Comment by tnodir** [comment]
What System Scale Percent do you have in the Display settings?

**Comment by tnodir** [comment]
I can reproduce it by setting the window's width to minimum.

**Comment by tnodir** [comment]
Thanks. Fixed by ef30b5f7.

**Comment by tnodir** [comment]
Please check [v3.10.5-test2](https://github.com/tnodir/fort/releases/tag/v3.10.5-test2).

**Comment by tnodir** [comment]
> But with Russian localization, one button is not aligned.

Let's leave it as is for now.

**Comment by tnodir** [comment]
Please check [v3.10.5-test3](https://github.com/tnodir/fort/releases/tag/v3.10.5-test3).
