### ISSUE TITLE
checkbox (multiple choice)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#165]
I have some difficulties:
After checking each checkbox, the menu disappears - this is somewhat inconvenient.
Also, I can't check/uncheck the box with a spacebar.

![mult-select](https://github.com/tnodir/fort/assets/11581901/dd89cf2f-4eca-45e4-999f-f1ecef9c5d07)

Perhaps this is not a bug, but a feature, but I don’t understand it.

**Comment by tnodir** [comment]
It's a feature. You can check/uncheck it with "Enter" key.
