### ISSUE TITLE
adding to group - there is no binary in the list

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#166]
1. open ie , open google.com
2. options - options - application group - group name = "speed limit" - add
![g01](https://github.com/tnodir/fort/assets/11581901/5a727b9b-df61-4106-bf0c-97328cc4f2a4)

3. program - ie- double click - application group = "speed limit" - ok
![g02](https://github.com/tnodir/fort/assets/11581901/6fb3f575-9251-4b47-b0f1-840c90a9a00a)

4. options - options - application group - select tab "speed limit"

result: 
empty "the right half is empty"
![g03](https://github.com/tnodir/fort/assets/11581901/020c7c82-c3e3-46e4-a715-a4c2549cfa23)

expected result
the right half contains "ie.exe"
![exe](https://github.com/tnodir/fort/assets/11581901/99d338a2-d8b7-401f-be8d-10dc809ffc25)

**Comment by Emi-Emi-Emi** [comment]
This is how it works.
Programs and Programs and Groups are Groups. Also, Programs take higher priority over Groups as well, so a rule for IE in Programs will override whatever you have in AppGroups, and if you want iexplorer.exe in a group, then you need to add it to a Group, not Programs.

`Use Application Group's Enabled State` for Speed Limit is more a temporary workaround today than anything else. There is this issue opened https://github.com/tnodir/fort/issues/93#issuecomment-1557230287

>I've a plan to add "Speed Limits" window.
>(It will work as "Zones" window.)
>
>So you will set Speed Limit to Programs.

So the plan is to move the Speed limit away from AppGroups and give it to Programs directly without the AppGroups, but they are still separated features for different purposes.

`Use Application Group' still has some usefulness like being able to Enable and Disable multiple programs at once, like groups, but without being groups and staying as Programs where it is easier to manage them, but they are still not AppGroups and will never be.

So this is not an issue, just the way Fort Firewall works.

**Comment by tnodir** [comment]
@b-user You can sett paths in App Groups as inline text or add paths in Programs window.

If you add same path to both Programs and App Groups, then Programs has higher priority (i.e. it overrides the App Groups).

Originally, there was not a Programs window in Fort.
