### ISSUE TITLE
Uncentered buttons in IP Addresses and AppGroups page.

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#168]
Using Fort Firewall v3.10.5-Test1, I noticed the 'lines editor' divider columns buttons are shifted to the left and not center anymore.

They also seem a little smaller looking at the "Add Local Networks" button.

![image](https://github.com/tnodir/fort/assets/152097351/3a27ca7e-6afb-4480-a8f2-e1313560d72d) ![image](https://github.com/tnodir/fort/assets/152097351/bc95b3dc-fdb7-4420-915b-48bd13392fc6)

**Comment by tnodir** [comment]
Thanks. Fixed by 686e1f1a.

**Comment by tnodir** [comment]
Please check [v3.10.5-test2](https://github.com/tnodir/fort/releases/tag/v3.10.5-test2).

**Comment by Emi-Emi-Emi** [comment]
Looking okay!
BTW the column resizing dots indicator is not centered either, in case it is not hard to adjust, but it is not an issue, just noticiable now that the buttons are centered.
