### ISSUE TITLE
Не блокирует Windows App

### ISSUE THREAD

**Issue by Onair-santa** [tnodir/fort#169]
Стоит режим блокировки всего, что не разрешено. Windows App легко выходят в сеть и нет ни вопросов, ни подтверждений, ни разрешений, ни записи если поставить режим обучения.
  Где-то недоработал тк это критическая ошибка для такой программы. Или я что-то не понял и тогда не прав.

**Comment by tnodir** [comment]
При таком режиме не должно быть доступа.

Если включить флаг "Блокировать Интернет траффик", то есть доступ?

Если нету, то через какое-то правило значит выходят. Скорее всего, сервис "Background Intelligent Transfer Service" (`\svchost\bits`).

**Comment by tnodir** [comment]
Если точно из-за сервиса BITS, то можно его заблокировать конечно. Но он также нужен для Windows Update.

**Comment by tnodir** [comment]
Если включить флаг "Блокировать Интернет траффик", то есть доступ?

**Comment by Onair-santa** [comment]
Да. Легко запускается и выходит при любых фильтрах.

https://github.com/tnodir/fort/assets/42511409/1de5020e-d251-4317-92d4-8d036ee34fb4

**Comment by tnodir** [comment]
Не видно на видео, флаг "Блокировать Интернет траффик" был включен?

**Comment by Onair-santa** [comment]
ХМ проверил, у меня и хром работает, фильтр такой
![image](https://github.com/tnodir/fort/assets/42511409/a3e3414b-6d46-4375-95fa-433be61e2b75)

**Comment by tnodir** [comment]
Значит через VPN идёт трафик?

**Comment by Onair-santa** [comment]
Нет. ВПН отключен. никакие сервисы не работают тоже. Интерфейс тоже только один Этернет. Хром полностью работает

**Comment by Onair-santa** [comment]
Версия 3.10.4 Портабл

**Comment by tnodir** [comment]
В окне "Мой Форт" чьто написано про Драйвер? Установлен?

**Comment by Onair-santa** [comment]
Да, установлено и иконка и зеленая и красная , в зависимости от фильтра. Интернет полностью работает, даже если включен фильтр.
![image](https://github.com/tnodir/fort/assets/42511409/27e832c7-2ac0-47d7-a17a-00ccf0d1e514)

**Comment by tnodir** [comment]
Можно скрин настроек из окна Options?

**Comment by tnodir** [comment]
Ещё скрин из Options: IP Addresses обеих вкладок.

**Comment by tnodir** [comment]
А если включить флаг "Блокировать траффик"? Тоже есть доступ?

Если нет доступа, значит намутили с адресами в Options: IP Addresses: Internet Addresses.

**Comment by Onair-santa** [comment]
![image](https://github.com/tnodir/fort/assets/42511409/c3f821ea-6648-45de-9de8-3748c5e0e38b)

**Comment by tnodir** [comment]
А почему отключили флаг "Включить все"?

Поэтому в "Адреса Интернета" не входят никакие адреса и ничего не блокируется.

**Comment by Onair-santa** [comment]
Понял.
А для чего эта настройка бестолковая? Есть же исключения, зачем еще и включение?
Я, кстати, по этому и не пользуюсь данной программой тк логически она не комфортна и пользоваться сложно.  В Симплволе все логично, все просто и на своих местах. Общие правила, свои правила и правила приложений. К чему эта ненужная иерархия? И зависимости всего от непонятно чего. Хочу создать правило для приложения, открываю окно, где кнопка + Создать правило? Кучи меню, пунктов....И так во всем. Перемудрил. Ладно извиняюсь.

**Comment by tnodir** [comment]
> А для чего эта настройка бестолковая?

Чтобы задать адреса публичного "Интернета" и не фильтровать адреса LAN (которые по-умолчанию заданы в Исключить).

Всем не угодишь. Спасибо за отзыв.

**Comment by tnodir** [comment]
Вообще, вкладка "IP Адреса" конечно перемудрена и будет удалена, когда сделаю "Сетевые Правила" #2.

Хотя, может быть останется только одно поле для задания адресов LAN. Без всяких Включить/Исключить.
