### ISSUE TITLE
units of measurement

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#170]
Please add other units of measurement.
For example megabits (not mebIbYtes).
![bit](https://github.com/tnodir/fort/assets/11581901/ad3abcc0-2bf0-480d-bf73-bd51f2bab995)

**Comment by tnodir** [comment]
Changed to bits-per-second by 42939474.

**Comment by tnodir** [comment]
Please check [v3.10.5](https://github.com/tnodir/fort/releases/tag/v3.10.5).
