### ISSUE TITLE
Explorer integration (for single/restricted user)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#171]
After integration with Explorer, all PC users have a context menu.
For multi-user OS this is somehow “wrong”.
I think it would be nice to be able to limit the integration to one user.

about here:
https://github.com/tnodir/fort/blob/1b6283e3be4f6b8f595f61d1b735693b59472662/src/ui/util/startuputil.cpp#L295

Additionally, Explorer integration is currently not available to limited users.

**Comment by tnodir** [comment]
Fixed by 471992a5.
