### ISSUE TITLE
context menu (unfinished localization)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#175]
In the "program" window, when editing the "name" there is a context menu in English.

![context2](https://github.com/tnodir/fort/assets/11581901/e1508cdf-0963-43a9-811a-e842bf62145e)

As example:

![co-copy](https://github.com/tnodir/fort/assets/11581901/71cbe0fe-38d4-491e-a85e-28ad76b24485)

![co-copy2](https://github.com/tnodir/fort/assets/11581901/9ac7f836-17c8-4a3a-8659-286fbcb09182)

**Comment by tnodir** [comment]
Fixed by a15d7977.
