### ISSUE TITLE
Service/Cлужба (localisation, ru)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#177]
В интерфейсе программы встречается термин "сервис".
Однако в русифицированном дистрибутиве windows данный термин повсеместно локализован как "служба" и известен пользователям в такой формулировке.
![srv](https://github.com/tnodir/fort/assets/11581901/35b0eb9f-371f-4b5e-8997-8ef18c8799ed)

В качестве примера предлагаю такой вариант:
![!s2](https://github.com/tnodir/fort/assets/11581901/3ed271f2-bc5c-4ef7-b1a8-fe6e26423e04)

Кстати об этом пункте.
Быть может имеет смысл сделать "всплывающую подсказку", как, например, в таком софте:
![!s-pop](https://github.com/tnodir/fort/assets/11581901/07b59b84-0c3d-4012-a557-40d65efc4f0d)

Так и интерфейс посвободнее и интересующимся предоставлена подробная подсказка (настолько длинная, что явно не впишется в статический интерфейс).

**Comment by tnodir** [comment]
Improved by 7f91a280.

**Comment by tnodir** [comment]
Please check the [v3.10.7-test3](https://github.com/tnodir/fort/releases/tag/v3.10.7-test3).
