### ISSUE TITLE
displaying “past” traffic when opening a new “traffic graph” window

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#179]
Sometimes I want to see what traffic was 30 seconds ago.
Currently, when opening a new “traffic graph” window, a window with empty data is displayed.
If possible, please implement such a function.

**Comment by tnodir** [comment]
Fixed by d7188461.

**Comment by tnodir** [comment]
Please check the [v3.10.7-test3](https://github.com/tnodir/fort/releases/tag/v3.10.7-test3).
