### ISSUE TITLE
Opening, an already opened Fort (through CMD or a Launcher) doesn't bring Fort/My Fort to the foreground, only the menu.

### ISSUE THREAD

**Issue by Emi-Emi-Emi** [tnodir/fort#180]
go to terminal and type "%programfiles%\fort firewall\fortfirewall.exe"

In my case My fort doesn't get opened in the foreground, only the menu is.

The keyboard doesn't work in Fort's menu either, to at least hit enter on something, so you are forced to use the mouse or alt+tab go to Fort that way to be able to select something with the keyboard, this is because Fort i snot the active window so in the case of terminal using arrows just go through the command history, also, the menu just stays floating on the screen until you click something on it as well, so it doesn't go away on its own or anything when clicking out or something.

![image](https://github.com/tnodir/fort/assets/152097351/76ff12c8-ef22-484d-875c-52a568e8ca75)

**Comment by tnodir** [comment]
Fixed by 80fe138b.

But it can fail to activate a window on 1-st open. Then you have to activate it by Alt+Tab.

**Comment by tnodir** [comment]
Please check the [v3.10.7-test3](https://github.com/tnodir/fort/releases/tag/v3.10.7-test3).

**Comment by Emi-Emi-Emi** [comment]
It seems like while it is better, but seems like it behaves were, sometimes opening with PowerToys Run will open it okay, sometimes open in background, just like opening from desktop icon or CMD.

Even if it was opened from Tray icon, it will fail, and then I restart, then it opens fine after opening though the floating menu, then it fails somewhere else.


https://github.com/tnodir/fort/assets/152097351/a757b6ff-213b-4200-adee-b956ecf808e2

I used desktop icon after recording video and it opened fine, so it is pretty random when it will open in the background, so it is better than before now it opens in the foreground as expected 95% of the time, sometimes it still goes for foreground sometimes it stays background but it is surely better and more consistent 👍

Maybe screen recording also helped, since it is like 'on top' of all windows, but seems better without it.

**Comment by tnodir** [comment]
Please check the [v3.10.7-test4](https://github.com/tnodir/fort/releases/tag/v3.10.7-test4).

It'll now always bring the window to top. But you have to press Alt+Tab to actually activate it, when needed.

**Comment by Emi-Emi-Emi** [comment]
Works much better, but the problem now is with My Fort menu and the Auto Show Menu, when you click on the menu, the menu now stays on top of other Fort windows, Auto Show Menu disabled, works great though.
![image](https://github.com/tnodir/fort/assets/152097351/687027ac-2a58-4ee8-86aa-5873ba4b3711)

**Comment by tnodir** [comment]
> the problem now is with My Fort menu and the Auto Show Menu, when you click on the menu, the menu now stays on top of other Fort windows

How to reproduce it?

**Comment by tnodir** [comment]
> the problem now is with My Fort menu and the Auto Show Menu, when you click on the menu, the menu now stays on top of other Fort windows

Fixed by f7302c78.

**Comment by tnodir** [comment]
Please check the [v3.10.7-test6](https://github.com/tnodir/fort/releases/tag/v3.10.7-test6).

**Comment by Emi-Emi-Emi** [comment]
Seems to work great now! 👍
Alt+tab still has to be pressed to activate keyboard, but only once the first time Fort is opened, and then it seems to work great afterwards.
Fort opens fine in the foreground, and auto show menu is not causing issues being on top and acting weird.

thanks!
