### ISSUE TITLE
множественно создание "предупреждающего диалога"

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#185]
STR:
* дефолтные настройки (RD /S /Q "data")
* portable (echo. >README.portable)
* запускаю fort  (start FortFirewall.exe)
* жду секунду пока запустится Fort (ping localhost -n 2)
* ожидаю пока в "программах" накопится несколько программ (или принудительно curl -I [www.ru](https://www.ru/) & aria2c http://www.ru/ & del index.html &  & nslookup www.ru 8.8.8.8) // уточнить про тестовую среду (aria2c)
* заполняю почти всё доступное место на диске (остаётся свободным ПРИМЕРНО 58 КБ) // уточнить про тестовую среду (утилька/скрипт)
* открываю окно fort "программы",
* выделяю несколько строк/программ (более одной)

нажимаю кнопку "разрешить" (2do вариации: или "блокировать, или "удалить")
 
![image](https://github.com/tnodir/fort/assets/11581901/a4b64732-96a7-43b4-89b0-933164027f42)

фактический результат:
множественное предупреждение
 
![image (1)](https://github.com/tnodir/fort/assets/11581901/f69db276-e00a-411f-94c0-94ed8db8fc7b)

 
ожидаемый результат:
единичное предупреждение

--
FortFirewall.exe.ini
[global]
logsDir=C:\\bin\\inet\\fort\\log
и наличие данное директории

**Comment by tnodir** [comment]
Fixed by a8d308d0.
