### ISSUE TITLE
the unavailable "block" button in the "application" window

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#186]
str:
open "app" window
click in an empty/white place
![image](https://github.com/tnodir/fort/assets/11581901/dad77587-dafb-482d-b5ff-746475729c89)
press ctrl+a

actually:
1. The fields are highlighted
2. The "allow/block/remove" buttons are **NOT** available

expected:
1. The fields are highlighted
2. The "allow/block/remove" buttons are **available**

**Comment by tnodir** [comment]
Fixed by 9151d882.
