### ISSUE TITLE
The wording "update checker"   / "проверка обновлений"

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#187]
Формулировка "update checker"  / "проверка обновлений" не выглядит очень понятной.
Да, существует wiki https://github.com/tnodir/fort/wiki/User-Guide#the-need-for-frequent-updates-and-wherehow-to-set-up-the-update , но не очень понятно зачем так всё усложнять.
На мой взгляд было бы достаточно изменить формулировку на "Проверка обновлений **Fort Firewall**", чтобы не было нужды читать wiki для понимания функционала данной галки.

![image](https://github.com/tnodir/fort/assets/11581901/e1bd429e-bc7e-44da-8379-a8f0e2ade022)
![image](https://github.com/tnodir/fort/assets/11581901/625b02e0-3544-4366-9294-a9145ef1b79f)

**Comment by tnodir** [comment]
Fixed by 1614caeb.
