### ISSUE TITLE
Improvement required for scrollbar visibility

### ISSUE THREAD

**Issue by PaperCutBad** [tnodir/fort#188]
@tnodir Right now it is harder to notice scroll position in the list because of less visibility. I think it could use a little tweak.
Chromium scrollbar to compare with fort firewall.
![Screenshot 2024-01-13 201522](https://github.com/tnodir/fort/assets/87314923/c07cdb75-0b04-4421-9d08-0a689d959c84)

**Comment by tnodir** [comment]
Depends on [QTBUG-120971](https://bugreports.qt.io/browse/QTBUG-120971).

**Comment by tnodir** [comment]
Slightly improved in [v3.10.12](https://github.com/tnodir/fort/releases/tag/v3.10.12).
