### ISSUE TITLE
Edit program dialog: Pressing OK does not apply the new name and and does not close the dialog

### ISSUE THREAD

**Issue by megabugman** [tnodir/fort#191]
Double Click to edit Program then Change the name. Press OK does not apply the new name and does not close the dialog:
![closebut](https://github.com/tnodir/fort/assets/17204819/d7193d42-1e7c-4029-90f4-3bf619d34f4e)

When pressing Cancel the dialog is closed and the new name is applied.

**Comment by tnodir** [comment]
Thanks, fixed by 0a38bbc3.

**Comment by tnodir** [comment]
Fixed in [v3.10.10](https://github.com/tnodir/fort/releases/tag/v3.10.10).
