### ISSUE TITLE
"Middle-click" on an icon (in the system tray) is interpreted as a "left-click" in Windows 11 (Build 22621.1344+).

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#195]
https://github.com/HavenDV/H.NotifyIcon/issues/82#issuecomment-1479437161

This is not a bug in Fort, but a Windows bug.

**Comment by rockenren** [comment]
> Should we just remove the "Middle Click" event?
> 
> And maybe add "Shift + Single Click".

if you planning to doing so, please, do it as an option.

**Comment by tnodir** [comment]
Ok, I'll not remove the "Middle Click" event while Qt has that in QSystemTray.
