### ISSUE TITLE
Release notes incomplete in My Fort

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#196]
As shown in the screenshot, there seems to be a small bug where not all changes are displayed in the My Fort window.

![image](https://github.com/tnodir/fort/assets/77551811/ec43721b-6443-4487-b625-efa2ba75d39f)

**Comment by tnodir** [comment]
Thanks, fixed by 2473be17.

**Comment by dashke** [comment]
Awesome, thanks for the quick fix!

**Comment by tnodir** [comment]
Fixed in [v3.10.12](https://github.com/tnodir/fort/releases/tag/v3.10.12).
