### ISSUE TITLE
LTSC Support

### ISSUE THREAD

**Issue by KarelWintersky** [tnodir/fort#197]
![изображение](https://github.com/tnodir/fort/assets/2164874/854c92f2-7440-4e48-8590-d41c5380a743)

My Win10 is 1809 (build 17763.5206).

Is it possible run `fort` on Win10 LTSC ?

**Comment by tnodir** [comment]
You have to install 32-bit version of installer, not 64-bit.

**Comment by KarelWintersky** [comment]
Nope, I downloaded 

https://github.com/tnodir/fort/releases/download/v3.10.13/FortFirewall-3.10.13-windows10-x86_64.exe

**Comment by tnodir** [comment]
@KarelWintersky It's a 64-bit version.

Use the https://github.com/tnodir/fort/releases/download/v3.10.13/FortFirewall-3.10.13-windows-x86.exe

**Comment by KarelWintersky** [comment]
It works. 
Add to FAQ, please

**Comment by tnodir** [comment]
Did you see a "[System Requirements](https://github.com/tnodir/fort/wiki/User-Guide#system-requirements)" link in the [README.md](https://github.com/tnodir/fort/blob/master/README.md)?

**Comment by tnodir** [comment]
Added https://github.com/tnodir/fort/blob/master/README.md#which-installer-should-i-download

Please review, is it clear for novice user?

**Comment by KarelWintersky** [comment]
Yeah, thank you!
