### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#198]
при отсутствии файла FortFirewall.ini ("в папке с конфигами")
экспорт завершается ошибкой

str:
окружение:  отсутствие конфигов ( директории "%LOCALAPPDATA%\Fort Firewall"  или "Data"  рядом с запускаемым FortFirewall.exe ) ; ~~обычный (не портабельный режим / отсутствие файла "README.portable" рядом с запускаемым FortFirewall.exe)~~

1. запустить  FortFirewall.exe (подробности не важны)
2. опции-опции-резервная копия
3. создать/выбрать пустую папку  (подробности опущены)
4. нажать кнопку "выбор папки"

фактически: "Невозможно экспортировать резервную копию" ; файлы резервной копии создались не все
ожидаемо: создались файлы резервной копии, предупреждения отсутствуют

PS. В логе "пустовато"/"что-то не то":
2024-01-28 11:03:09.659 W conf: Export file error from: "C:/Users/U/AppData/Local/Fort Firewall/FortFirewall.ini" to: "C:/bin/inet/firewall/Fort Firewall/777/FortFirewall.ini"

**Comment by tnodir** [comment]
Thanks, fixed by 5963539d.
