### ISSUE TITLE
Simplify "Show Program Alert Window"

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#202]
**Issue:**
The "Show Program Alert Window" functionality in the firewall currently has an extensive array of options, which might be overwhelming for users who prefer a more straightforward experience. This feature request is to streamline the interface by providing a simplified view with basic "Allow" and "Block" buttons, while also incorporating a user-friendly way to access more advanced options.

**Description:**
The current design of the "Show Program Alert Window" in the firewall includes numerous options, potentially making it challenging for users who prefer a more simplified interface. To enhance user experience, I propose the following changes:

1. **Basic Interface:**
      _Allow:_ A prominent button for quickly allowing the program.
      _Block:_ A straightforward button to block the program.

2. **Access to Expert Options:**
Introduce a button (e.g., "Advanced Options") that users can click to access more intricate settings for advanced users.
This should open a secondary window or dropdown, offering additional settings such as custom rules, port configurations, and more.

Thank you for considering this feature request.

**Comment by tnodir** [comment]
Please check the [v3.11.1-test1](https://github.com/tnodir/fort/releases/tag/v3.11.1-test1).

**Comment by tnodir** [comment]
Please check the [v3.11.1-test2](https://github.com/tnodir/fort/releases/tag/v3.11.1-test2).

Also you can use "Ctrl+O" to open an advanced options menu.

**Comment by tnodir** [comment]
Implemented in [v3.11.1](https://github.com/tnodir/fort/releases/tag/v3.11.1).
