### ISSUE TITLE
💀⚡️💀⚡️

### ISSUE THREAD

**Issue by cocainumusys** [tnodir/fort#203]
![18317204](https://github.com/tnodir/fort/assets/157902299/03bbea28-84be-4376-a63c-16aa88ce67cb)

_**Cрочное обращение к разработчику!!!**_

**Виндоус оповещения - это, как ночной кошмар .**

**Comment by tnodir** [comment]
Отключите флаг Опции: "Оповещение о новых программах через Системные сообщения".

А почему кошмар?

**Comment by cocainumusys** [comment]
> Отключите флаг Опции: "Оповещение о новых программах через Системные сообщения".
> 
> А почему кошмар?

Да потому-что они всех бесят, вечно закрывают пкм в трее. Надо что-то пугающее, чтобы знать кто там в дверь стучится и, конечно же, наглядная информация в окне о этом процессе(как, например - от 
Malwarebytes)

**Comment by tnodir** [comment]
Попробуй [v3.11.1-test0](https://github.com/tnodir/fort/releases/tag/v3.11.1-test0): добавил флаг для авто-показа окна оповещения.

> наглядная информация в окне о этом процессе

Потом что-н. этакое добавим.
