### ISSUE TITLE
UI: Programs: Reorganize Parked/Scheduled columns — wrong columns description.

### ISSUE THREAD

**Issue by rockenren** [tnodir/fort#204]
Fort 3.11.1, updated from 3.11.0

Descriptions for columns in Programs window are in wrong order and messed up.

![image](https://github.com/tnodir/fort/assets/11333307/1e1786f0-d772-4668-aec8-85a962608c27)

**Comment by tnodir** [comment]
Thanks, fixed by 51056910.

**Comment by tnodir** [comment]
Please check the [v3.11.2-test0](https://github.com/tnodir/fort/releases/tag/v3.11.2-test0).

**Comment by rockenren** [comment]
Can confirm, issue is resolved.

**Comment by ahdung** [comment]
So what is parked plz?
