### ISSUE TITLE
Can't resize columns

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#206]
Unfortunately, I am not able to resize the following columns in the last update v3.11.1 -
![image](https://github.com/tnodir/fort/assets/77551811/88dc6b2b-e76d-4f29-a070-2deaa925cfeb)

**Comment by tnodir** [comment]
These 2 columns have fixed size and not resizable.

But header descriptions are messed up in last release.

Please check the [v3.11.2-test0](https://github.com/tnodir/fort/releases/tag/v3.11.2-test0).

**Comment by dashke** [comment]
Awesome, thanks for the ultra fast fix!

**Comment by tnodir** [comment]
Fixed in [v3.11.2](https://github.com/tnodir/fort/releases/tag/v3.11.2).
