### ISSUE TITLE
Programs window is not responding for 2 or 3 seconds on first open

### ISSUE THREAD

**Issue by fifaplayer88** [tnodir/fort#213]
After I reboot my PC and open the FortFirewall (Programs) window, when I try to click or select any Application, I noticed that the window become laggy and not responding for seconds, after that it becomes normal. this always happen after reboot or start FortFirewall for first time.

**Comment by fifaplayer88** [comment]
System information
Window11 23H2 22631.3085
SW:FortFirewall-3.11.4-windows10-x86_64
Monitored 4K

**Comment by tnodir** [comment]
Duplicate of #49
