### ISSUE TITLE
Dark theme for UI

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#22]
Add dark theme for all UI.

(Extracted from #18)

**Comment by tnodir** [comment]
See:
- https://github.com/Alexhuszagh/BreezeStyleSheets
- https://github.com/ColinDuquesnoy/QDarkStyleSheet

**Comment by anwar-alsilwy** [comment]
Well, you will implement it on upcoming releases, or I suppose to do it by myself ?
I don't think I can do it.

**Comment by tnodir** [comment]
I’ll implement it later.

**Comment by tnodir** [comment]
Added as experimental feature in [v3.6.0](https://github.com/tnodir/fort/releases/tag/v3.6.0).

**Comment by anwar-alsilwy** [comment]
Great job 👍
But I have a little suggestions:
1- unavailable options text is too dark and difficult to read, they will be better if they become little more brighter.
![1](https://user-images.githubusercontent.com/71539261/184511225-5559c944-4a7a-4389-953e-8e067e8d59fd.png)

2- selected tabs is pure black, you can change it to dark gray.
![2](https://user-images.githubusercontent.com/71539261/184511367-39c8df68-9871-41f1-8d98-a728317d6d4b.jpg)

3- make the color of tray menu identical to the windows menus color.
![3](https://user-images.githubusercontent.com/71539261/184511438-ad79e00c-f217-41b5-b6d0-647be4bd5d6b.jpg)

Good luck my friend 😊

**Comment by tnodir** [comment]
@anwar-alsilwy Thank you for testing the Dark Mode.
Actually I've just added ability to use Qt's dark mode support, which is [in progress](https://bugreports.qt.io/browse/QTBUG-72028) right now.

**Comment by anwar-alsilwy** [comment]
👍

**Comment by tnodir** [comment]
Fort follows system dark mode from [v3.6.2](https://github.com/tnodir/fort/releases/tag/v3.6.2).

Dark mode style will be improved by [Qt](https://bugreports.qt.io/browse/QTBUG-72028).
