### ISSUE TITLE
Allow/block the path by command line argument

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#231]
It's possible now to use `FortFirewall.exe -c prog add <PATH>` to open a Program Edit dialog.

Also add ability to allow/block a path by not opening the dialog: `FortFirewall.exe -c prog {allow|block} <PATH>`.

**Comment by WGZero05** [comment]
> It's possible now to use `FortFirewall.exe -c prog add <PATH>` to open a Program Edit dialog.
> 
> Also add ability to allow/block a path by not opening the dialog: `FortFirewall.exe -c prog {allow|block} <PATH>`.

This is so cool then. Please do it. The sooner the better. I too want to block programs with no gui window. Only in silent mode. 🙏🏻 Thanks! 🙇🏻‍♂️

**Comment by WGZero05** [comment]
Please also include how to block ip addresses without opening the fort firewall. thanks!

### e.g: FortFirewall.exe -c prog {allow|block} <172.0.0.1>

**Comment by WGZero05** [comment]
> > Please also include how to block ip addresses without opening the fort firewall.
> 
> Sorry, it's out of scope for now.
> 
> I'm adding ability to set Rules for Programs (address/ports/etc) at the moment. But addresses will be assigned to Rule, not Program.

sorry ma bad. I mean blocking ip adresses in rule and not in program. Same as in Windows Firewall inbound and outbound. I had blocked ip adresses in my windows firewall 2 months ago and I've decided to block them as well with ur amazing app.

**Comment by Emi-Emi-Emi** [comment]
This is working great, nice addition!

I used it with PowerToys Run and it was nice not to have to open the UI just to allow or block a program for few seconds.

But terminal makes it easier to manage programs, with scripts and all that, so the more CMD support the better, especially since Windows started supporting OpenSSH out of the box, where editing the DB through terminal was not the easiest thing to manually add programs and all that.

is it possible to do this with wildcard programs too?

**Comment by Emi-Emi-Emi** [comment]
@tnodir how do you deal with wildcard programs that have multiple programs on it? seems to work when single path wildcard programs when you add the wildcard character paths, but how to handle the _multiple paths_ wildcard programs?

**Comment by Emi-Emi-Emi** [comment]
@tnodir oh nice workaround! I usually add comments in my wildcard programs, but didn't test that.
Using comments also helps to workaround wildcard programs with variables paths too if anything.

Thanks, amazing feature as always! 👍

**Comment by Emi-Emi-Emi** [comment]
Oh I see, I get what Fort is doing now! I went ahead and re-saved all wildcard apps, so I can see even variable paths work and all .👍; and then comments just make it easier to handle wildcard programs. Thanks again!

**Comment by ahdung** [comment]
@tnodir  Thank you, so where can I find these commands? I tried /? not help.
