### ISSUE TITLE
State of IPv6

### ISSUE THREAD

**Issue by ViRb3** [tnodir/fort#24]
Hello,

Absolutely love this project! The wildcard file path matching and per-service resolution are one of a kind, I never thought I would see this possible. Just one question - what is the current state of IPv6? I noticed that it's absent from the UI and you have it in your TODO list, but at the moment, what happens to IPv6 connections? Do app filters work on them? Are all IPv6 connections automatically allowed/blocked?

Many thanks

**Comment by tnodir** [comment]
Hi

> I noticed that it's absent from the UI and you have it in your TODO list

Yes, indeed.

> what happens to IPv6 connections? Do app filters work on them? Are all IPv6 connections automatically allowed/blocked?

IPv6 connections are not handled (filtered) now, so they will be auto-allowed or handled by default Windows Firewall.

(Personally I just disable IPv6 protocol in the network adapter settings.)

**Comment by ViRb3** [comment]
Thanks a lot for the clarification. I would recommend writing this in the README, since it is a potentially unexpected bypass of the firewall.

**Comment by tnodir** [comment]
Thanks, added to [FAQ](https://github.com/tnodir/fort/wiki/FAQ#state-of-ipv6).

**Comment by tnodir** [comment]
Let the task remain open until it is implemented.

**Comment by anwar-alsilwy** [comment]
> (Personally I just disable IPv6 protocol in the network adapter settings.)

I disabled IPv6 protocol in the network adapter, but guess what ?
As you know, The Tor proxy using IPv4 to establish Tor connections to bypass blocked sites, so Tor works great with only IPv4.
But if we want to visit (. onion) sites, we need to enable SecureDNS, and that's require IPv6 to be enabled, see below:

![Untitled](https://user-images.githubusercontent.com/71539261/168419435-81f496bb-8051-477e-aa14-78ce8d53fdb1.png)

**Comment by tnodir** [comment]
Implemented in [v3.5.7](https://github.com/tnodir/fort/releases/tag/v3.5.7)
