### ISSUE TITLE
Error when install driver & start service

### ISSUE THREAD

**Issue by anwar-alsilwy** [tnodir/fort#25]
Hi
I tried to install FortFirewall for my friend PC, he has windows 10 build 1909_x64 with UEFI boot, and disabled secure boot.
But the driver won't install and the service unable to start, also he installed latest VC++ x86 & x64, as you can see:
![20220514_081943](https://user-images.githubusercontent.com/71539261/168412733-b9e4d1a7-8783-49e4-a97b-ecc67362de54.jpg)

Any suggestions please ?

**Comment by tnodir** [comment]
You’ve to instal 32-bit installer. The 64-bit installer, which you’re trying to install, is for Windows 2004•.

**Comment by anwar-alsilwy** [comment]
Oh, I see
Sorry, I didn't read the README.md page carefully.
Thanks a lot.
