### ISSUE TITLE
Small question about Service

### ISSUE THREAD

**Issue by anwar-alsilwy** [tnodir/fort#31]
I'm just thinking, is there any idea to prevent FortFirewallSvc from stopped by user, like "Access Denied" or something,
I like the password idea and stop anyone using my internet without my knowledge, but anyone who end the service process can bypass all filters.
I'm just asking, I don't want to waste your time anymore.

**Comment by anwar-alsilwy** [comment]
> Only users in Administrators group can stop the service.

I'm administrator, but also I tried to terminate some of system services, and says "Access Denied"

> OTOH, you can turn on the "Stop traffic when Fort Firewall is not running" option.

You mean it will stop traffic even if I kill the FortFirewallSvc or just FortFirewall.exe !!??

**Comment by tnodir** [comment]
> I'm administrator, but also I tried to terminate some of system services, and says "Access Denied"

Because they're specially configured (e.g. to run as LocalService user).

But Fort's Uninstaller should remove the service as admin.

> You mean it will stop traffic even if I kill the FortFirewallSvc or just FortFirewall.exe !!??

Yes, it will.
This feature is mainly to block traffic during system boot until Fort runs.

**Comment by anwar-alsilwy** [comment]
Now I understand,
In my opinion, FortFirewall is better than Simplewall, its more advanced with driver and traffic graph and much more.
Except "Network Rules" which is on progress now I guess.
BTW,  Stop traffic when Fort Firewall is not running" option, works great.
Thanks bro.

**Comment by anwar-alsilwy** [comment]
At last, is there a hotkey to enable/disable traffic ... etc ??

**Comment by tnodir** [comment]
> At last, is there a hotkey to enable/disable traffic ... etc ??

Turn on the "Hot keys" option and add to user's .ini in [hotKey] section for example:
```
stopTraffic=Ctrl+Alt+Shift+S
stopInetTraffic=Ctrl+Alt+Shift+I
```
