### ISSUE TITLE
FortFirewall: Zone from local file

### ISSUE THREAD

**Issue by GrandFa** [tnodir/fort#32]
После добавления правил из локального файла, могу ли я этот файл удалить?

**Comment by GrandFa** [comment]
Добавление зон
![Screenshot_220525_195059](https://user-images.githubusercontent.com/53760601/170318141-90af022c-e718-4579-8342-2deb361cfbc1.png)
.

**Comment by tnodir** [comment]
Удалить можно, если не планируется обновлять.

**Comment by GrandFa** [comment]
Понял.
