### ISSUE TITLE
Start as a Service

### ISSUE THREAD

**Issue by GrandFa** [tnodir/fort#33]
Какие приемущества даёт опция "Запускать Fort Firewall как Сервис в фоне"

**Comment by tnodir** [comment]
- Файрвол будет работать даже если никто не залогинен. И напр. обновление винды может проходить в фоне.
- Кто-то не хочет видеть или не хочет светить значок файрвола в трее.
- Админ ставит файрвол как Сервис и настраивает правила доступа, а другие юзеры не имеют к файрволу доступа.
