### ISSUE TITLE
Network Rules and Documentation

### ISSUE THREAD

**Issue by udhay111** [tnodir/fort#34]
# Network Rules Greyed out
May be my issue sound silly, please let me know how to work in Network rules.

![Pic_01](https://user-images.githubusercontent.com/76847070/172061327-4e940da1-9175-407a-8dfa-dc116be403d8.png)

# Please add documentation
If possible please add documentation to explain important things to be considered to sucessful implementation for IT

**Comment by tnodir** [comment]
It's a work in progress, see #2.

**Comment by tnodir** [comment]
> If possible please add documentation to explain important things

See Wiki & Discussions. PR-s are welcome.

**Comment by udhay111** [comment]
THANKS @tnodir for the reply I understand a lot work is to be done so for so good please keep the good work.
