### ISSUE TITLE
BSOD 0x00000192 on win 2016 

### ISSUE THREAD

**Issue by esuslik** [tnodir/fort#37]
I have bsod after installing fort firewall and latest updates for win 2016 server
0x00000192: KERNEL AUTO BOOST LOCK ACQUISITION WITH RAISED IRQL

There are no bsod if i delete fortfw.sys from system32\drivers

**Comment by tnodir** [comment]
@esuslik Which ISO should I use?
- en_microsoft_hyper-v_server_2016_updated_feb_2018_x64_dvd_11636751.iso	2.67 GB
- en_windows_server_2016_essentials_updated_feb_2018_x64_dvd_11637999.iso	4.54 GB
- en_windows_server_2016_updated_feb_2018_x64_dvd_11636692.iso	5.59 GB
- en_windows_storage_server_2016_updated_feb_2018_x64_dvd_11636738.iso	4.45 GB

**Comment by esuslik** [comment]
What is HVCI feature&

i used SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_Russian_-3_MLF_X21-30363.ISO
After install fortfirewall i install updates i gave the bsod

**Comment by esuslik** [comment]
hvci not enabled

**Comment by tnodir** [comment]
I've installed the `SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_Russian_-3_MLF_X21-30363.ISO`.
And reproduced the BSOD.
Investigating...

**Comment by esuslik** [comment]
error started since v3.5.7

**Comment by esuslik** [comment]
error occure on rdp connection to this server. 
there is no error with local login to server.
Tested on VM

**Comment by tnodir** [comment]
@esuslik Please check the [v3.5.9-test02](https://github.com/tnodir/fort/releases/tag/v3.5.9-test02).

**Comment by tnodir** [comment]
@HGhostRevisionist88 Can you please re-test "Apply same rules to child processes" feature in the [v3.5.9-test02](https://github.com/tnodir/fort/releases/tag/v3.5.9-test02)?

**Comment by HGhostRevisionist88** [comment]
@tnodir Everything working as expected, made sure to do it with different ways of launching programs, through Explorer, XYPlorer, Flow Launcher, then Terminal and individually through Powershell, CMD, and also made sure I had a long list of child processes to make sure everything worked fine. 👌

**Comment by esuslik** [comment]
Everything work great
