### ISSUE TITLE
msvcp140_1.dll error on Windows 10

### ISSUE THREAD

**Issue by CHEF-KOCH** [tnodir/fort#4]
Why you use old and outdated [Visual C++ 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) instead of a modern version? 

Modern versions also run on Windows 7. I ask because even if you install the runtimes on Windows 20 it will trigger the "missing msvcp140_1.dll error" on startup. 

You should consider to use modern standards.

**Comment by tnodir** [comment]
> Why you use old and outdated Visual C++ 2015 instead of a modern version?

I'm using latest MSVC 2019 (16.4.5) compiler to build Qt and program.
I've to investigate why it depends on msvcp140*.dll

> I ask because even if you install the runtimes on Windows 20 it will trigger the "missing msvcp140_1.dll error" on startup.

Please install 32-bit runtime too.

**Comment by tnodir** [comment]
https://community.amd.com/thread/240570
"Visual Studio 2015 and later versions of Visual Studio all use one Universal CRT."

So, just install latest **_vc_redist.x86.exe_**
