### ISSUE TITLE
wondering if... BSOD

### ISSUE THREAD

**Issue by bluelayer** [tnodir/fort#47]
Hi!

just got one "UNEXPECTED KERNEL MODE TRAP" when turned on my computer... wondering if this is coming from FF? I updated yesterday to 3.7.1 without issues.

**Comment by bluelayer** [comment]
> Hi, can you please send the crash minidump to [nodir.temir@gmail.com](mailto:nodir.temir@gmail.com)?

I have them disabled, if happen again I will let you know.

**Comment by tnodir** [comment]
I've got same BSOD when restarting on Windows 10 update.

Last version uses KeDelayExecutionThread() to wait other thread on driver startup.
I've changed it to proper KeWaitForSingleObject(event) now in 3677c598.

**Comment by tnodir** [comment]
Fixed in v3.7.3
