### ISSUE TITLE
Slow PC: Programs window is not responding for 2 or 3 seconds on first open

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#49]
After I reboot my PC and open the FortFirewall (Programs) window, when I try to click or select any Application, I noticed that the window become laggy and not responding for seconds, after that it becomes normal. this always happen after reboot or start FortFirewall for first time.

(Extracted from #46)

**Comment by tnodir** [comment]
I'll try to emulate a slow PC with [BES](https://mion.yosei.fi/BES/).

**Comment by tnodir** [comment]
Similar issue [neovim-qt/issues/614](https://github.com/equalsraf/neovim-qt/issues/614).

**Comment by fifaplayer88** [comment]
I also have this issue 
System information 
Window11 23H2 22631.3085 
SW:FortFirewall-3.11.4-windows10-x86_64

**Comment by tnodir** [comment]
> Window11 23H2 22631.3085

From which `.ISO` did you install Windows, maybe some repack?

I've to install from same `.ISO` in VM to reproduce the bug.

Please run `dir /B %windir%\fonts > fonts.txt` command and attach the `fonts.txt`.

**Comment by fifaplayer88** [comment]
> > Window11 23H2 22631.3085
> 
> From which `.ISO` did you install Windows, maybe some repack?
> I have from Windows Update to 22631.3085 Build 
> I've to install from same `.ISO` in VM to reproduce the bug.
> 
> Please run `dir /B %windir%\fonts > fonts.txt` command and attach the `fonts.txt`.
> How to run  this command for windows OS 
> If you installed some additional fonts, then what they are?

I  installed Windows language is chinese 
I find any FortFirewall version also have this issue  such as [Fort Firewall v3.11.0]

**Comment by tnodir** [comment]
> How to run this command for windows OS

- press Win+R or click Start: Run to open a `Run Command` dialog
- type `cmd.exe` and `Enter`
- type `dir /B %windir%\fonts > fonts.txt` and `Enter`
- attach the newly created `C:\Users\<USER-NAME>\fonts.txt` file here

**Comment by tnodir** [comment]
> I have from Windows Update to 22631.3085 Build

I've installed English version of Windows 23H2 22631.3007 and installed Chinese language pack.

I can't reproduce the bug with selected Chinese language.

**Comment by tnodir** [comment]
@fifaplayer88 What disk do you have? HDD or SSD?

**Comment by fifaplayer88** [comment]
> @fifaplayer88 What disk do you have? HDD or SSD?

I have SSD and HDD with PC,but system ISO installed SSD, other files with HDD

**Comment by tnodir** [comment]
> I have SSD and HDD with PC,but system ISO installed SSD, other files with HDD

- where is the `Windows` installed?
- where is the `Fort Firewall` installed?

**Comment by fifaplayer88** [comment]
> > 我的PC有SSD和HDD，但是系统ISO安装了SSD，其他文件用HDD
> 
> * 安装在哪里`Windows`？
> * 安装在哪里`Fort Firewall`？

安装在哪里`Windows`？ SSD
安装在哪里`Fort Firewall`？SSD
<img width="1472" alt="屏幕截图 2024-02-13 175934" src="https://github.com/tnodir/fort/assets/44253636/46bb4d83-5ff0-470a-b1a9-e137c885d08f">

**Comment by fifaplayer88** [comment]
> > but system ISO installed SSD
> 
> Please say, Windows 23H2 22631.3007 installed on SSD?
YES

**Comment by tnodir** [comment]
@fifaplayer88 Can you please check your SSD (on which Windows installed): what is the *reading* speed from it?

**Comment by fifaplayer88** [comment]
> I don't understand why Disk is "e" Disk "c" is "hdd"?

I have two SSD disk one disk is 256G  other disk is 1T,I split a 1T hard drive into two partitions.

**Comment by fifaplayer88** [comment]
> @fifaplayer88 Can you please check your SSD (on which Windows installed): what is the _reading_ speed from it?
 
I'm sorry  I didn't express myself clearly

I have two SSD disk one disk is 256G other disk is 1T,I split a 1T hard drive into two partitions

256G > installed Windows ISO   1T 1T hard drive into two partitions > installed Fort Firewall for E disk 

Please check refer to picture   
<img width="358" alt="1" src="https://github.com/tnodir/fort/assets/44253636/ec6fa9a2-d872-4fdf-ace5-88ddddde877f">
<img width="370" alt="2" src="https://github.com/tnodir/fort/assets/44253636/0da73d83-798e-4a32-8c4d-1acf4db4a0fb">

**Comment by tnodir** [comment]
> I have two SSD disk one disk is 256G

Thank you for information and screenshots.

And what is your CPU?

**Comment by fifaplayer88** [comment]
> > I have two SSD disk one disk is 256G
> 
> Thank you for information and screenshots.
> 
> And what is your CPU?
Please check refer to infromation  
CPU AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
RAM:32.0 GB
Monitor 4K 3840X2160 152Hz

**Comment by fifaplayer88** [comment]
> @fifaplayer88 Ok, I'm going to add Splash screen on Fort's startup (to force Qt to process fonts).
> 
> So, the Programs window will work as expected later.

I just find  mouse also have is not responding for 2 or 3 seconds with on reboot PC and Startup FortFirewall

**Comment by tnodir** [comment]
> I just find mouse also have is not responding for 2 or 3 seconds with on reboot PC and Startup FortFirewall with background

Do you mean that mouse is not responding for 2-3 seconds system-wise? Not only in Fort's Programs window?

**Comment by fifaplayer88** [comment]
> > I just find mouse also have is not responding for 2 or 3 seconds with on reboot PC and Startup FortFirewall with background
> 
> Do you mean that mouse is not responding for 2-3 seconds system-wise? Not only in Fort's Programs window?

I find reboot PC and Startup FortFirewall with background on first time mouse also is not responding for 2-3 seconds

**Comment by tnodir** [comment]
@fifaplayer88 Please check the [v3.11.5](https://github.com/tnodir/fort/releases/tag/v3.11.5).

**Comment by tnodir** [comment]
@fifaplayer88 Please check v3.11.6 with Splash screen showing on startup. Does it help with the bug?

**Comment by fifaplayer88** [comment]
> @fifaplayer88 Please check v3.11.6 with Splash screen showing on startup. Does it help you?
> @tnodir thanks for your reply
We try to installed V3.11.6 find below question
1.I find PC from Shutdown to boot this issue is cannot reproduced.
2.I find PC from reboot to boot this issue is also reproduced but V3.11.6 is improve not responding times is acceptable

**Comment by fifaplayer88** [comment]
> @tnodir  
I hope you can continue improve this issue with next version,
Thanks

**Comment by tnodir** [comment]
> I hope you can continue improve this issue with future versions

I can't reproduce the bug, so I can't work on it.

Splash screen is just a workaround for now.
