### ISSUE TITLE
 error when build driver

### ISSUE THREAD

**Issue by hongruixing** [tnodir/fort#5]
development environment    vs2019 + wdk10  
found the error when build  debug version ,but no error while release version
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _assert referenced in function align_down	fortdrv	D:\vs2017\fort\src\driver\fortdrv.obj	1	

Microsoft Visual Studio Professional 2019
Version 16.6.4

Windows Driver Kit   10.0.19030.1000
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

**Comment by tnodir** [comment]
Please check with 5427666a4

**Comment by tnodir** [comment]
Fixed by f4035e4
