### ISSUE TITLE
Password disappears

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#50]
[ Bug ] When I enable password function, It works just fine but sometimes without known reason, password disappear and become completely open, and that's weird.

(Extracted from #46)

**Comment by tnodir** [comment]
@anwar-alsilwy How does the Password editing field look after password disappearing?

**Comment by anwar-alsilwy** [comment]
Actually:

1- What I meant about password disappear, is no longer password message appear, As if I didn't set the password in the first place, So everything open without password protection
After password message disappear issue happened, I open (Options) window and put new password on password field, then password function works again.

2- I didn't check {passwordHash} in the FortFirewall.ini yet, I'll do it tomorrow on free time, my apologies.

3- No, I didn't change "Unlock till" option, it's default

**Comment by tnodir** [comment]
@anwar-alsilwy Can you reproduce this bug with v3.7.2?

**Comment by anwar-alsilwy** [comment]
This morning, password function works great, but I'm sure it has a bug, it happened twice ( on my PC, and my friend modern PC),
By the way, when password message disappeared the password field become (not installed) that's all I remember so far.
Great thanks

**Comment by tnodir** [comment]
Password disappears after Quota alert. Fixing...

**Comment by tnodir** [comment]
Fixed in v3.7.3
