### ISSUE TITLE
Filter local address disabled while stop service 

### ISSUE THREAD

**Issue by anwar-alsilwy** [tnodir/fort#55]
On my FF settings,
1- I enabled filter local addresses
2- I disabled local ip address from list #127.0.0.1
3- I choose " Stop traffic when FF stoped" option

When I ping to 127.0.0.1 via cmd it says failed which means the local address is blocked.

But when we stop fortfirwallSvc, the traffic will stop on all applications, but if we ping to 127.0.0.1 via cmd it says Reply, which means the filter of local addresses is stop working

**Comment by tnodir** [comment]
Implemented in [v3.8.1](https://github.com/tnodir/fort/releases/tag/v3.8.1).

**Comment by anwar-alsilwy** [comment]
> Implemented in [v3.8.1](https://github.com/tnodir/fort/releases/tag/v3.8.1).

Great thanks 👍

I enabled filter local addresses, stop traffic when FF is not running options and put #127.0.0.1 to exclude ip addresses, then stop FF service and ping to 127.0.0.1:
General failure.
That's good,
But did you apply this new change on 127.*.*.* only or even 255.255.255.255 too ??

**Comment by tnodir** [comment]
> But did you apply this new change on 127...* only or even 255.255.255.255 too ??

To both 127...* and 255.255.255.255

**Comment by anwar-alsilwy** [comment]
> To both 127...* and 255.255.255.255

Ok, very nice

So, now I will test if this new change will conflict with "Walk on LAN" feature while booting,
Stay tuned master tnodir .....

**Comment by tnodir** [comment]
Keep in mind, the standard Windows Firewall (WFw) has built-in rules for 0.0.0.0 address.
If the WFw is not disabled, then it'll actively try to connect to DHCP server on startup.

**Comment by tnodir** [comment]
If you find any bug with this feature, then please create new issue.
