### ISSUE TITLE
Enable Filtering even when app is closed.

### ISSUE THREAD

**Issue by HGhostRevisionist88** [tnodir/fort#6]
I finally decided to try your Firewall recently after watching it grow in wilderssecurity for months and I think it is great, but there is one thing I don't understand about the firewall and it is: how Fort Firewall has to be opened all the time for it to work and do the the filtering and apply the rules we set.
I thought that by installing the driver, it would keep running in the background, which it seems to be able to do when using "stop traffic when Fort Firewall is not running", but then I had to opened it for it to work and then when closing it it just starts allowing all the connections again.

Not the end of the world but It would be nice if Fort Firewall could keep running in the background at all times and do the filtering even when app is closed, just like how other firewalls do it. I mean, I know since Fort Firewall doesn't write 'persistent' BFE rules in the registry like other firewalls so it is intended to work work differently but I just don't think having to run the firewall at all times in the tray is the best experience, especially when Start with Windows is not even on by default and the only work around would be to use the Stop traffic when fort firewall is not running so a connection we don't want allowed doesn't get allowed, also closing a program is so easily done by a crash or by stuff like Taskkill and not even admin rights so anyone could easily get rid of Fort Firewall and that would be a security risk. I mean, having to run fort firewall in order to work makes sense when portable mode, but not when I want to use it as the main firewall replacing the Windows native one.

It is just a feature request. I know it is not the end of the world and it doesn't make the firewall impossible to use, I know some people would suggest "keep using simplewall or Tinywall (and wait for Tinywall to do IP filtering)", but I like what I see in your firewall and would like it to improve it.

Thank you and have a good day.

**Comment by tnodir** [comment]
I’m adding ability to run it as a service right now...
Thanks.

**Comment by tnodir** [comment]
I was going to quickly add interactive service, but it's impossible on Windows 10 [1].
I'll look, what can I do...

[1] https://docs.microsoft.com/en-us/answers/questions/27517/is-there-any-workaround-in-win10-to-allow-service.html

**Comment by HGhostRevisionist88** [comment]
It is great if you are already working on it.
A nice feature to have for sure, that and a more advanced way to allow/block programs (by local/remote port and IP range, protocol, direction) would make the Firewall really amazing to replace any other Firewall because not having to run Fort Firewall exe all the time and still get the job done would make things nice easier. So I appreciate the effort.

Thanks for your work and hope it will not be too much work to implement.
Good luck!

**Comment by tnodir** [comment]
The feature is almost done and tested.
I'm waiting for new Certum certificate to release new version.

Would you like to test it? I can pre-release it.
(But you will have to backup an old profile to return to older version.)

**Comment by HGhostRevisionist88** [comment]
> Would you like to test it? I can pre-release it.
(But you will have to backup an old profile to return to older version.)

Sure. Last time I was thinking I wish you had a beta release from time to time to test new changes and features, especially this one. So many of my apps run the beta version so no problem about testing and start over and backing up profiles and all that. 👍

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc0

**Comment by HGhostRevisionist88** [comment]
testing the preview build works mostly great!
Ran into few issues and even got to break it stuff around to test how much I can break it and then how to fix it in case that happens.

But one of the issues I encountered was a crash when a new program was getting blocked and then the tray icon displays the attention exclamation mark on it. And then that would lead to weird behaviors because the process that crashed wouldn't get closed and then 2 process would exist for the firewall besides the one for the service, so I had to terminate the process manually. (there are some crashdumps generated for that if you need them).

The main issue I found was how when you install it as service (after manually start Fort as admin), you can't delete or reinstall the driver, it will just not work, so the only way to reinstall the driver was to uninstall Fort as service and then do it when on Localappdata.

But the first time I tried to troubleshoot that was because for some reason I broke the service or maybe it was after the crash, but I wasn't getting new blocked apps registered or new entries in the Blocked Connection tab in (now) statistics window, first running as admin seemed to make it work but then after a while I noticed the service was stopped and that's how I started to really check on that, I just ended up reinstalling the service and driver.
But the problem is how you can't uninstall the driver because I was getting Service isn't available, but service wasn't starting because "dependency error" for something about the driver, so I ended up going back to normal mode and delete the driver and service with Process Hacker.

I was still curious about what happened, so I decided to test how to edit the database to modify timestamps and the order of found apps. So I stopped the service manually since there is no way on the UI to do it unless you remove Fort as service, which would delete the settings. 
But sometimes doing that (and sometimes because of the crash and the process still on without me knowing) for some reason the config-shm and config-wal didn't get removed (or merged or whatever happen to them), so then I would get a "Load Settings:unable to open database file" and the service would break and stay stopped and throw the dependency error. So I guess I had to clean manually those wal and shm files and then everything worked fine.

But it's great to be able to use Fort without having to run it, everything works nicely, if service is closed then connection is closed (with the setting about stop network when Fort is closed), it keeps checking apps so when I open them I go to apps and see what failed to connect to network no problem about how the service is supposed to do its job by keeping the firewall running without the tray icon to stay on and only use the firewall to config and whitelists apps and be able to close it again.

Nice job!
Of course I will keep running it and see if something breaks without me messing too much with it, just using it normally without manually stopping the service or editing the database or anything like that.

**Comment by tnodir** [comment]
> The main issue I found was how when you install it as service (after manually start Fort as admin), you can't delete or reinstall the driver

I forgot about it. I'll fix it, thanks.

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc1

**Comment by HGhostRevisionist88** [comment]
Ok!
Now uninstalling and installing driver works on Service mode.
There are some stuff I can point out: for example, when driver is uninstalled, it will also uninstall the service, which means, if for whatever reason a person uninstalls the driver and closes fort, then it will go back to normal mode, and that means that the settings will be wiped.
If driver is uninstall and then installed (to reinstall the driver like reinstall.bat does) while the app is opened, then the settings are kept while reinstalling the driver and the service. I guess, maybe the button should say "reinstall" if the driver is detected as installed?

But that's the same issue why upgrading wipes the settings, upgrading fort will remove the service and driver and reinstall it, but then it will go back to normal mode, and then making Appdata be wiped when going to service mode.

Of course backed up the Appdata, but there is one thing about doing that, the service has to be manually closed for files to be replaced with the old settings, and if the service isn't started before opening Fort as non admin, then the problem will seem broken and display the "service not available" only when you try to save settings. But no warning or anything before that when you start Fort. So it is either, close Fort and open it as admin which will start service or manually start the service Fort and then open fort either way admin or not, which pretty much would take the same time since there is not a button to restart Fort as admin or the program asking for admin rights if it detects the service not running, or doing something that requires admin (like going from normal mode to service mode).

Of course, I wouldn't call my notes: "issues", but I point them out trying to put myself in other people's shoes who might get confused or don't troubleshoot as I would
Everything is working fine to me, there are no issues in the way Service mode is working, even restarted to test and it works fine, as expected, service executable doesn't crash or anything, so no issues about it.

**Comment by tnodir** [comment]
> I wouldn't call my notes: "issues", but I point them out trying to put myself in other people's shoes who might get confused

It's all are valid concerns. I was thinking how to fix these issues too.

**Comment by tnodir** [comment]
> The only real crash I have experienced is when detecting new apps but that's on a Fort instance opened normally, not the service, I even forced the crash after opening 10 apps and getting blocked by Firewall

Can you please describe step by step how to reproduce the crash?

**Comment by tnodir** [comment]
> I was thinking how to fix these issues too.

So my plan:
- Create "%ProgramData%/Fort Firewall/README.service" on first Service install.
- Check on startup that Service is installed or the README.service exists. If the Service is not installed and the file exists, then auto-install and run it.

What do you think?

**Comment by tnodir** [comment]
I've done simpler:
- Use "%ProgramData%/Fort Firewall/" by default if it exists.
- Options: Driver: Hide "Remove" button, rename "Install" to "Reinstall".

**Comment by HGhostRevisionist88** [comment]
> Can you please describe step by step how to reproduce the crash?

Not really, seems like it is random. I opened Fort normally and I have the Fort tray icon to be displayed in the taskbar, then I only see it displays the icon alert to tell me something was blocked and and when I am going to click on it, the icon disappears, but no log about it or anything. To reproduce it once yesterday, I just deleted the whole list in Programs and left the couple ones I would need to have connection, so it would detect all programs again and eventually after a while the icon disappeared when I was going to click on it, but it was different programs and all that, deleting the list of Programs again so they get blocked again, doesn't produce the same result. It affects only the normal Fort and not the Service, so internet won't stop working with the option to stop internet when fort is not running, haven't had a problem with it and my pc runs 24/7.

>Use "%ProgramData%/Fort Firewall/" by default if it exists.
Options: Driver: Hide "Remove" button, when Service installed; Rename "Install" button to "Reinstall".

Yeah I think that will simplify and make things more and better, because in my mind, if someone install it as service, why would anyone want to remove the driver? I understand if someone somehow wants to switch from service to normal mode, but the only situation I can imagine when someone would want to remove the driver is if they are using it as portable and want to make sure driver is removed without using the scripts. Even if Fort is installed I don't see why people would remove driver, if they want to uninstall Fort, but people do weird things lol
I see people wanting to reinstall it because for some reason it broke (I don't know why), but if that happens to anyone the Reinstall button should be perfect.

Of course, I would think that adding the option of installing Fort as a service mode in the installation will remove even more confusion, I would even add Recommended next to it so people choose it if they want the best experience.

**Comment by tnodir** [comment]
> I opened Fort normally and I have the Fort tray icon to be displayed in the taskbar, then I only see it displays the icon alert to tell me something was blocked and and when I am going to click on it, the icon disappears, but no log about it or anything.

Is the Service installed?
Which windows was open?
Which options are on (Collect stats, blocked connections etc)?

Does it crash for *no* Service mode?

Please turn on the Options: Logs: Log debug messages. It'll log some events for service.

**Comment by HGhostRevisionist88** [comment]
yes, I have been running Fort as a service since you released the RC.
And I opened Fort but closed all windows so it would just stay in tray, I never saw it crashing when Programs or any other window was opened, only when a program was blocked, the tray icon changes icon and I just was going to click on it to go to Programs or right click and click on programs and the icon just disappeared, but I never lost connection since the Service kept running.
I haven't tested it for no Service mode has the same random crash issue, but I only experienced it 3 times in the many hours I have been running Fort, of course, now I can run it on the background I don't really have it opened, but it happened after blocking apps.

I will turn logs and see what happen, and re-block more apps to see if there is some info that can be useful.

**Comment by tnodir** [comment]
> Which options are on (Collect stats, blocked connections etc)?

I've turned on the "Collect blocked connections" option and set to keep 1K rows.
The program crashed some time later.
It looks like it was after removing old connections..

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc2

It includes Google Breakpad to generate crash minidumps.
"<logs-path>/crash_fort_*.dmp" files will be generated on crash.

**Comment by HGhostRevisionist88** [comment]
ok! testing it, I was trying to hard to get crash with RC1 earlier, even had 4 terminals opened doing infinite ping so the blocked connections would get filled quickly for like 6 hours and nothing.

Everything worked perfectly (which is a good thing though).

If I get a crash on this version I will upload the crash minidump.
Thanks.

**Comment by tnodir** [comment]
Hurray, I've caught a crash. Checking..

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc3

It should fix the QPixmap's crash.

**Comment by tnodir** [comment]
> To easily test it: If you go to Fort Programs and remove apps often like you remove them, then they appear again and you remove them again, eventually Fort will break, it will not register more blocked connections or blocked apps.

Hm, I can't reproduce it.

> When Fort is restarted, the Auto Scroll and Show Host Names don't work

Thanks, let me fix this regression.

**Comment by HGhostRevisionist88** [comment]
> Hm, I can't reproduce it.

oh I can easily do it. I have couple ping command running that get blocked, so System is getting blocked often, and other apps and like Brave Tor implementation that tries to connect often, so I guess like 2 or 3 apps as soon as I delete the apps, so I delete, they appear, I delete and they appear. and eventually you will see they stop appearing and that means Fort just went to that freezing state where nothing will happen unless service gets restarted.
I used both, del key and remove on the UI and it triggered it just the same, also did it by removing 1 app at the time or multiple apps at a time and same, ctrl+a can be a weird thing to use since apparently I have to select 1 app first, but it triggered this issue faster.
I also tested backed up and newly created config, Fort did that weird stuff the same so it wasn't like my old settings doing a conflict.

I will record a video if you can't reproduce it. But I am using Win10 19042.985 just in case that has anything to do.

BTW I could get the whatever issue I have when right clicking on tray icon, I am sure it is not a crash anymore but a weird behavior with the click menu. Because sometimes when I right click, the popup menu will immediately disappear, you see it and then gone, not even time to react to it but after that I notice options get checked or unchecked from it, like if I was clicking on the menu, but it triggers with my mouse movement not with like a click, so something is doing the "click". So I guess that is the issue that causes the app to quit, not a crash but it is 'clicking' on quit button without me doing it.
That happens sometimes when I open windows or use left click to open Programs or double left click to open Settings, maybe I left click and right click too fast and move my mouse so maybe it kinds of clicks on the menu rather than doing nothing, but sometimes it happens with only right click, but the menu doesn't behave or feel the same way, it feels like it takes a while when I click for that to happen, like if Fort was doing something and then it has to wait for that to end for the menu to appear, but instead is like rushing things and then opens the menu without doing the other thing and then if my mouse is on the quit button, Fort quits.

I can't really explain it better, but I could trigger it often by using left click and then right click immediately, sometimes the right click menu would appear before the window appears and while it doesn't close Fort 100% of the times, it happens really often.
In comparison, other programs don't display the right click menu if I left and right click quickly, it will open the window but never the menu while Fort seems to do both which causes this weird behavior.

Of course apparently it is caused  by me clicking way too fast, so not a real Fort issue. Sometimes I meant to right click and not left click and end up doing both too quickly which can cause trouble with how Fort works.

I guess I am more likely to get these weird "issues" than others for impatience and fast typing or clicking and doing many things at once, which means it won't affect 99.99% of people. sorry about that!

**Comment by HGhostRevisionist88** [comment]
Hi,
Got a crash today, I was testing Zones because I had no idea what it was about until today, so I wanted to see if WindowsSpyBlocker firewall rules worked with it, in case I ever want to use it something like that, well, it works great but only  WindowsSpyBlocker/tree/master/data/firewall lists are compatible, others will give a "bad mask" on the log because they have a comma at the end of the IP.

Anyway, apparently when I added the update.txt one, the URL I pasted wasn't correct, maybe I missed a character or something when I copied/pasted it, but when I tried to update the zones, log threw the expected: TaskZoneDownloader: "WindowsSpyBlocker - Update" : "Error at line 1: Bad format" because I don't know which URL was using, but then totally crashed Fort Service. Of course it was my fault since re-adding the URL and making sure it was the correct one works fine.
But it was crash after all and since it was the service, it has to be manually started and client has to be re-opened since it was giving the "service not available".

I wouldn't think it is a big deal, because it only crashed once even if I click the update button multiple times, because log shows Bad Format like 5 times, but in case you want to see it here is:
[crash_fort_svc.dmp](https://onedrive.live.com/download?cid=D2697FD4DA07B1D6&resid=D2697FD4DA07B1D6%2194182&authkey=AC-_TOxx6PYYNF0)


Also, just something else I noticed it and I don't know if you have noticed it but the Windows Explorer integration doesn't work if Fort is running only as service and client is closed. I don't even use that integration but installed it since it is checked on the installer, but tested it to see what happened and I had the client closed and then didn't get any popup or anything. In case you didn't know about it. I don't want to miss saying information that might be useful for you in the future.

**Comment by tnodir** [comment]
> Got a crash today, I was testing Zones

Sure, Fort never should crash. Let me fix it.

> the Windows Explorer integration doesn't work if Fort is running only as service and client is closed.

Yes, this's also by design.
It tries to send command to running service's client (or program without service), which will open the Edit Program dialog.
Maybe we should show warning, that there is no running Fort.

**Comment by tnodir** [comment]
> Got a crash today, I was testing Zones

Tried various URLs, but can't reprodice it. Crash dump doesn't contain useful info.

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc4

**Comment by HGhostRevisionist88** [comment]
Testing it!
But yeah, I tried adding URL that wouldn't be correct, I only saw the Last Success, in zones blank but no crash, I thought the crashdump would be useful, but it sucks it wasn't. I only see new curl error codes in log 6 and 3 and 1, but no crash.
the only weird that has happened about Fort lately is how I found a blank dmp generated file in Fort logs folder, it had some weird hash as filename, but it was done at 5:22 am, where the only thing that runs in this computer is a task with 'nircmd.exe' with argument 'monitor off' and I found in Windows AppData\Local\CrashDumps this [FortFirewall dmp.](https://onedrive.live.com/download?cid=D2697FD4DA07B1D6&resid=D2697FD4DA07B1D6%2194183&authkey=AAAxkRxYtIX9DMY)

I also saw a tiny little thing with Fort Zones updater: if you run the Update the first time, it will update the addresses and tell you how many address the zone you are adding contains, but then if you run the update a second time, they will be replaced with 0.

But everything seems to be working fine so far, no crash when adding a bad URL or anything to zones having Fort in the same way when it crashed. But it's nice you added Spy.txt as a source so quickly!
I thought the update.txt one was wrong or didn't work with Fort, since it was giving trouble and even a crash, but who knows what my URL had, I tested without h in https, double pasted URL and even with a space after the .txt and all of them didn't work, displayed in log but no crash, I also edited the config database to let Fort seem like it was the first time doing it and deleted cache files and all that, so I guess it is good a crash won't happen anytime soon and it was only a one time thing. 👌

**Comment by tnodir** [comment]
>  it was done at 5:22 am, where the only thing that runs in this computer is a task with 'nircmd.exe'

It crashed when Fort was closing. This bug fixed in RC4 by https://github.com/tnodir/fort/commit/2bd992bd12b119e5ef6b66d6b9def1b40780f501.

**Comment by tnodir** [comment]
> I was testing Schedule tab, I wanted to add zones with bad URLs and let it update hourly to see if I ever got a crash or something, but apparently scheduler only works once, the first time it checks the updates, after that it doesn't try to update anymore.

You can force update by clicking on Run button in the Schedule tab, i.e. not wait for hour.

1. Does the "Last Run" change?
2. If you mean that "Last Success" is not changing, then it's fine, because Zone's sources at URL wasn't changed too.

  Zone Downloader downloads a text from URL and checks its checksum with existing. If they're equal, then "Last Success" will not be updated.
  If there are no `curl` errors in the logs, then it's Ok - just Zone sources are not changed.
  You can change Zone's URL to test this logic.

**Comment by tnodir** [comment]
> the first time it checks the updates, after that it doesn't try to update anymore.

Oh it looks like there is a bug with saving the Enabled state of Zone.
That's why it wasn't run..

**Comment by HGhostRevisionist88** [comment]
The issue is that I set it to 1 hour, it does it every 2 hours, so ran at 11:30pm as expected by me, but then it did it at 1:30am, 3:30, and 5:30.
So it seems like only when information in DB like last run or last success and checksums were Null, it would respect the 1 hour interval and run at the expected time, but once it checked the update and added the information in the database, it would then start doing it every 2 hours.
But now I see a change in the Last Run every 2 hours, so it technically works fine.

**Comment by tnodir** [comment]
Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc5

Please try to crash it with reported bugs.

**Comment by HGhostRevisionist88** [comment]
No crashes so far, and things seem like they are behaving better, like I haven't even gotten any tray menu problems or anything. I tested blocked connections window with many ping processes and stuff so it generated fast blocked connections and the auto scroll worked fine same as show host names, so no crash about it. I am still testing like updating Zones with bad URLs, and letting the schedule to do it as well, even if it does it every 2 hours, it will do the job while I am away from computer. But it is working fine and no crashes about it either.

The only issue I tested and I can still reproduce is how service gets totally bugged when updating the program list by deleting blocked apps. But I made a video so you can see the easiest way to reproduce it, but you don't have to do that for it to happen, it is random and the first part of the video was like I had my old settings allowed and blocked apps, so I removed them and restarted Fort client, so apps got blocked again but I had to remove allowed rules and anything that could slow blocked connections and when I did that and cleared the Programs list again then service got broken easily. [Video](https://onedrive.live.com/download?cid=D2697FD4DA07B1D6&resid=D2697FD4DA07B1D6%2194184&authkey=AKET4nISKUyTr2w)

But it is working good and no real crashes or anything, but service will keep running and whatever crash happens I will report it.

**Comment by tnodir** [comment]
> The only issue I tested and I can still reproduce is how service gets totally bugged when updating the program list by deleting blocked apps.

Thanks, I've reproduced it. Fixing..

**Comment by tnodir** [comment]
> The only issue I tested and I can still reproduce is how service gets totally bugged when updating the program list by deleting blocked apps.

It was a nasty bug. Fixed.

> letting the schedule to do it as well, even if it does it every 2 hours

Now it'll check tasks each 5 minutes, not 1 hour.

Please test: https://github.com/tnodir/fort/releases/tag/v3.4.0-rc6

**Comment by HGhostRevisionist88** [comment]
Just wanted to say that I have been running RC6 since you posted it 24/7 and no problems with crashing or anything anymore.
Service mode works great, good job 👌

**Comment by tnodir** [comment]
@HGhostRevisionist88 Thanks for testing. I'm too in service mode.

I've a problem with installing new Certum certificate, so release is postponing..

**Comment by tnodir** [comment]
Implemented in v3.4.0
