### ISSUE TITLE
Bluescreen issue 

### ISSUE THREAD

**Issue by kareem007g** [tnodir/fort#66]
First of all. Think you Mr. Tnodir. For This powerfull program.. Iam having bluescreen of death. When turn pc by wake on lan. This issue happend  to me before the last two realses (3.8.5 and 3.8.4), even after the last two releases. the issues still happening... I hope you can fix This problem
![IMG_20230408_211458](https://user-images.githubusercontent.com/61616299/230741564-84aab24d-a01b-4924-b8d6-c906c504710f.jpg)

**Comment by tnodir** [comment]
Do you have a Hibernate mode?

Please send dump file from C:\Windows\Minidump\ to nodir.temir@gmail.com

**Comment by tnodir** [comment]
Does it crash on normal boot too?

**Comment by kareem007g** [comment]
Thank you Mr tnodir for your replay. I have hibernate and fast startup activated.
Iam not sure the bluescreen show up  In normal boot or normal sleep. but i will test it and let you know.

**Comment by tnodir** [comment]
I've activated hibernate and fast boot on my notebook, but still can't reproduce the BSOD.

What Fort Firewall's options do you use?

**Comment by kareem007g** [comment]
I have tested on normal boot by power button and its happend after shutdown the pc two time, on the Thered boot BSOD showed up. After that. I tray to reproduce the BSOD BUT IT didn't showed up .also i tested on restrart  after 4 to 7 time BSOD showed up.

**Comment by tnodir** [comment]
@kareem007g Please check [v3.8.6](https://github.com/tnodir/fort/releases/tag/v3.8.6).

**Comment by kareem007g** [comment]
I will tested and let you know

**Comment by tnodir** [comment]
So you can reproduce the BSOD with v3.8.6?

**Comment by bluelayer** [comment]
just got  UNEXPECTED KERNEL MODE TRAP when updating from 385

**Comment by kareem007g** [comment]
> So you can reproduce the BSOD with v3.8.6?
> 
> Which FFw's Installer are you using, 32- or 64-bit version?

Its only showed up once. Then i can't reproduce BSOD. I Installed ffw's 32 version. On windows 10 20h2 i think. I will install FFw 64 bit  and test it.

**Comment by tnodir** [comment]
> just got UNEXPECTED KERNEL MODE TRAP when updating from 385

@bluelayer I've to fix stack usage of some other functions then..

**Comment by kareem007g** [comment]
After i updated FFw's 3.8.7  x64. I tray many time to reproduce the BSOD.  And its never show up. The issues .(UNEXPECTED KERNEL MODE TRAP)
has been fixed

**Comment by kareem007g** [comment]
Also i notice there is Another Three  BSOD error 
The First one  its only showed up once and its happend when i shutdown the pc . 
![IMG_20230413_181740](https://user-images.githubusercontent.com/61616299/232183042-a198fdc8-62d0-4b8f-b6f7-c9ccb13bfd91.jpg)
  
The second one  happend from time to time 
BSOD 
 (IRQL Not Less or Equal)

And  the last one  its always showing up. I dont know if FFw's have anything to do with it 
BSOD 
(memory mangment )

**Comment by tnodir** [comment]
@kareem007g Please check the [v3.8.8](https://github.com/tnodir/fort/releases/tag/v3.8.8).
I've fixed old bug in the driver.

**Comment by tnodir** [comment]
Please check [v3.8.9](https://github.com/tnodir/fort/releases/tag/v3.8.9).

**Comment by kareem007g** [comment]
> Please check [v3.8.9](https://github.com/tnodir/fort/releases/tag/v3.8.9).
I Installed ffw's 3.8.9 64x After 8 time BSOD 
![IMG_20230419_060852](https://user-images.githubusercontent.com/61616299/232963173-28ec1a13-a8f6-40d0-9a7a-342353f97a39.jpg)

showed up. I sended the dump to you. Also there is  Another BSOD massge. Show up after 30 to 50 mintus . On ffw's 3.8.8.. But i forgat to delete old dump file 
![IMG_20230418_232645](https://user-images.githubusercontent.com/61616299/232964703-b53e5551-adb8-4fdc-a246-a61768536ff8.jpg)

**Comment by tnodir** [comment]
@kareem007g Did you get the KERNEL_DATA_INPAGE_ERROR error ever before? Or does it occur after FFw installation only?

It looks like a [drive error](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7a--kernel-data-inpage-error):
> "0xC000000E, or STATUS_NO_SUCH_DEVICE, indicates a hardware failure or an incorrect drive configuration. Check your cables and check the drive with the diagnostic utility available from your drive manufacturer. If you're using older PATA (IDE) drives, this status code can indicate an incorrect master/subordinate drive configuration."

For example, try to physically move your HDD from SATA port 1 to port 2.

**Comment by kareem007g** [comment]
This error KERNEL_DATA_INPAGE_ERROR. I only swa it after i updated ffw's i think from 3.8.5 to up

**Comment by kareem007g** [comment]
The  BSOD still happening UNEXPECTED_KERNEL_MODE_TRAP. I dont know why This happening to me. This is my pc specification (core i5 6 gen-ram 8 ddr4 ) iam using windows 10 ghost spectre 64x

**Comment by tnodir** [comment]
> iam using windows 10 ghost spectre 64x

Is it this one: http://ghostspectre.the-ninja.jp/20H2.X64.html ?

**Comment by tnodir** [comment]
@kareem007g I've installed the Ghost Spectre x64 on VM, but can't reproduce the BSOD.

Please try the [v3.8.12-test02](https://github.com/tnodir/fort/releases/tag/v3.8.12-test02).
Will it crash on installation?

**Comment by kareem007g** [comment]
I have tested ffw's 3.8.12. After many of traying to reproduce BSOD its never showup.the BSOD (UNEXPECTED_KERNEL_MODE_TRAP) has been fixed. Thank you Mr tnodir for your hard work

**Comment by tnodir** [comment]
@kareem007g Please keep running the 3.8.12-test02.
Will the KERNEL_DATA_INPAGE_ERROR occur after some time?

**Comment by kareem007g** [comment]
Ok i will keep using.
 Do you think mr's tnodir the BSOD error (memory mangment)  casuse by ffw's

**Comment by tnodir** [comment]
> Do you think mr's tnodir the BSOD error (memory mangment) casuse by ffw's

Yes, it can be caused by older FFw versions.

**Comment by kareem007g** [comment]
I noticed that it happend after 40 mintus or more. While i am playing games. It's show up In the midal of games, i don't remamber that i saw it in normal use

**Comment by kareem007g** [comment]
i installed  FFW 3.8.12 latest x86 on  windows 10 1909  64x. the  BSOD (UNEXPECTED_KERNEL_MODE_TRAP) showed up

**Comment by tnodir** [comment]
OK, let me remove some dangerous functions (KeStackAttachProcess/KeUnstackDetachProcess & PEB handling) from driver and move services detection logic to user-mode...

**Comment by tnodir** [comment]
@kareem007g Please check the [v3.8.13](https://github.com/tnodir/fort/releases/tag/v3.8.13).

**Comment by tnodir** [comment]
Ok, I’ve to do smth with the UNEXPECTED_KERNEL_MODE_TRAP BSOD…

**Comment by tnodir** [comment]
@kareem007g Please check the [v3.8.15](https://github.com/tnodir/fort/releases/tag/v3.8.15).

**Comment by tnodir** [comment]
@kareem007g [v3.8.16](https://github.com/tnodir/fort/releases/tag/v3.8.16) should fix the BSOD, please check.

**Comment by kareem007g** [comment]
d
