### ISSUE TITLE
App is closed.

### ISSUE THREAD

**Issue by kolanp** [tnodir/fort#7]
Selecting an option from the tray icon will cause the program to close itself.

**Comment by tnodir** [comment]
Which option?

**Comment by kolanp** [comment]
The problem was solved by installing VC_redist.x86.exe. everything is OK.
I'm translating into korean. I'm not sure these strings.
Please explain the exact meaning of each word.
Zone, Axis, Tick label, Sum

**Comment by tnodir** [comment]
> The problem was solved by installing VC_redist.x86.exe.

I've added optional link for it to Installer's last page.
Maybe Installer should check VC libs existence too and open the link unconditionally..

Anyway there should be a warning message about missing DLL, after selecting the Options from tray icon.

> Please explain the exact meaning of each word.

- Zone: zone contains IP addresses, e.g. some block list
- Axis: graph's axis
- Tick label: graph tick's label
- Sum: sum of bytes

> And please contact me using an email

nodir.temir@gmail.com
