### ISSUE TITLE
Option to make Fort not to minimize or close to tray and make Hotkeys non-global [Feature Request].

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [tnodir/fort#72]
Hey @tnodir I hope you are doing okay, it's been a while since I created an issue for Fort! (old account was HGhostRevisionist88)

I would like to request a little tiny setting, so Fort Firewall will open as window and also minimized in taskbar, not like an active window in the foreground when FortFirewall.exe is launcher, and then when the close button is hit, the Fort client will close and don't go to tray.

The reason I don't want Fort to minimize to tray on the start or close, is because sometimes I create a quick hacky kiosk mode in some computers by closing explorer.exe so they can't have access to anything so they don't try anything, but then, when FortFirewall.exe is opened, it either will say Fort is already opened or open it on tray, which means I would have to open explorer.exe to have access to it, which I don't want since I do it remotely and don't know who is looking, you can't just trust anyone.

I know about the Hotkeys and found them in source to set them up, but they have to be global, which works great, but can you make hotkeys local instead of global as well, so they only work when Fort is active? 
I am not fan of global hotkeys because for example, ctrl+m mutes the mic on Skype, but it is also used in Brave to mute the tab, so unless I disable global hotkeys in Skype, it would mute the mic all the time when I try to mute tabs.
So it would be nice if Fort could also work with hotkeys but on the local level, because sometimes I use programs that have too many hotkeys and I am not sure when I will trigger something in those programs for wanting to check something in Fort or vice versa.

Because I can use global hotkeys to have access to Fort without the tray, but it would be nice if I could just open FortFirewall.exe through a launcher or CMD and get Fort already accessible with the Alt+Tab, without having to move my mouse, and then be able to use Fort hotkeys without worrying about triggering anything anywhere else.

Hope you are doing great! and thanks for your work, Fort is still the best, and love the new Kill Process feature, might use it even if it goes against your warning of being careful! 👍

**Comment by tnodir** [comment]
@Emi-TheDhamphirInLoveUnderTheFrozenStar I missed your valuable feedback, I’m glad you’re still using Fort.

I was busy in fixing bugs and BSOD’s after refactorings. So now I can continue to work on new features.

About this feature request: I think it’s reasonable and easy to implement.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
I am glad you think it is easy to implement, it should be helpful in many situations, and maybe. improve someone else's workflow other than mine. 😁

And yes! Fort is still the best for the cool features you have implemented that other Firewalls don't have, and that balances the few missing features to implement that others might have and might be useful once or twice. Surely like some of the improvements you have added in the last year. Other Firewalls are bloated, underdeveloped/seem dead, or just a Windows Firewall skin, which sucks because when you block outbound connections, some apps like UWP will get whitelisted when they update, the only good thing about WF is: Powershell integration and policies to deploy the rules easily across computers and don't let anyone mess with anything, and I will take Fort Firewall features over that and use the policies to disable the Windows Firewall.

But yes, always appreciated how great you are with users feedback for sure.

**Comment by tnodir** [comment]
I doubt how to name the new window: Dashboard or Control Panel?

(Agnitum Outpost named it My Security.)

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
I like Dashboard more, while Control panel would also be fine, if you want to display more information in the future to that page, then Dashboard would make more sense.
Control Panel seems like it would be more where settings would be changed, like the NVIDIA one, and Fort already has the Options window for that, so it would be a conflict in the name, if we think deeply about it, where I guess new page has to be like a launcher, and for example even Xbox UI is called Dashboard or Home.

Unless you want to call it My Fort, but then, just like Agnitum Outpost, it won't say much only how it has to do with Security.

**Comment by tnodir** [comment]
> I kind of like it, sounds kind of personal, and has the feeling type of thing of battles from ages ago or like an RTS game with a fort ready to defend an attack.

I like it too, thanks :)
So I'll name it `My Fort` in UI, and `HomeWindow` class in code.

**Comment by tnodir** [comment]
Implemented in [v3.9.1](https://github.com/tnodir/fort/releases/tag/v3.9.1).
Please check.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Oh nice, nice implementation to have Fort in the screen without the tray icon! That was quick! Thanks.

Anyway! It's working great in the state it is now, just there are few comments and little things I found to give feedback about, and I am sorry in advance for being picky. 👍Everything is working great though! It's a general 3.9.1 feedback not just about My Fort.

My Fort/Tray icon:
1. It would be nice if the buttons are shown, instead of having to click Menu in My Fort, but I guess this is something you plan to do later, since this is first release with it, but I am still mentioning.

2. I think there should be more text than "Show Icon" in Options, since it is not explaining much what it does, because it is not only about the Tray Icon but how it will also completely close when the last window is closed and after that it will show My Fort as the starter page from now when the program is opened, so it also affects like the startup process since starting computer will show my fort like that, instead of just a tray icon.

3. There needs to be a prompt, show a message, show an icon next to the setting, something to restart Fort or tell the user to do it when the Tray Icon is disabled, because if not, then Fort will not work as intended and say It will say "Application already running", so there should be a way for user to know they have to restart it in order to see it in action, so closing Fort through the tray icon is the only way or on computer restart.


Other stuff:
1. And found an unrelated bug to My Fort: when you set password to Fort, and you middle click the tray icon, then it always opens Programs window and not the Statistics one, Ctrl+Click opens Options fine though.

2. Unrelated My Fort Feedback: I think there should be a way to ask for old password to update to a new password or when someone wants to disable it, just to make sure the person who opened the window or knows the password is the one changing the password.

3. Also, I have a question: Is it hard to bring Fort to the front when showing the already running message? I hide the taskbar and sometimes I forget to completely close it, so I see the message, and then I have to see where in the alt+tab it is, but it would be nice if Fort was in the taskbar it would show the message and bring it to front.
Can this be a thing or is not a QT thing?

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Nice release, everything is great, Fort is better without the 'already running' warning for sure, as well!
Thanks for implementing My Fort, you are the best! 👍

**Comment by tnodir** [comment]
> 4. Local hotkeys only work in My Fort ...

I'll replace the "Options" button with "Menu" in the Programs window in next release.
So local hot keys will work in Programs too.
