### ISSUE TITLE
Tabs move/bug when creating/switching groups in Application Groups.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [tnodir/fort#74]
Happens when creating groups and then switching, the only normal one is the default Main group.
Testing it with new Fort Data to discard being caused by other settings.

![FortFirewall_2023-05-03_13-00-06](https://user-images.githubusercontent.com/122518587/236017209-18f76fb2-d7e4-4035-88a3-d373a4c8a695.gif)

**Comment by tnodir** [comment]
It's a regression in Qt: [QTBUG-113376](https://bugreports.qt.io/browse/QTBUG-113376).

**Comment by tnodir** [comment]
Fixed in [v3.9.0](https://github.com/tnodir/fort/releases/tag/v3.9.0) - temporarily reverted QTabBar changes, until Qt team fixes it.
