### ISSUE TITLE
please: basic example

### ISSUE THREAD

**Issue by denisdemaisbr** [tnodir/fort#8]
input:
- deny all

output:
- allow all
- except: bad-remote-site.com
- except: bad-remote-ip
- except: bad-remote-netowork

**Comment by tnodir** [comment]
You can't filter on direction (input/output) now. It'll be implemented in #2

> except: bad-remote-site.com

You can not filter by host name, only by IPv4 addresses.

> except: bad-remote-ip

You can:
- create Zone for it with file and set it to App. Group
- or just add the address to Options -> IPv4 Addresses -> Allowed Internet Addresses -> Exclude

> except: bad-remote-netowork

You can add IPv4 addresses range too.
