### ISSUE TITLE
New version notification remains after update

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#86]
It seems that for some reason the new version notification stays in the GUI.

![image](https://user-images.githubusercontent.com/77551811/237036403-d6188568-8e5c-4ee9-b73d-8004cdec44c7.png)

Steps to reproduce:
1. Download version 3.9.1
2. Run the update checker to get 3.9.2 (can't do this now as the newer version is out)
3. Manually download and upgrade to 3.9.3

**Comment by tnodir** [comment]
Fixed in [v3.9.3](https://github.com/tnodir/fort/releases/tag/v3.9.3).
