### ISSUE TITLE
Traffic graph GUI enhancements

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#87]
- Please add an option to change the transparency.
- Please add a dark mode, or even better, an option for the user to customise the colours of the graph itself.

**Comment by dashke** [comment]
After having discussed this with you, please move the Options to a new Tab.

**Comment by dashke** [comment]
Please also add a 'Reset to default' button to reset the colors in the Traffic Graph tab.

**Comment by tnodir** [comment]
Implemented in [v3.9.4](https://github.com/tnodir/fort/releases/tag/v3.9.4).
