### ISSUE TITLE
Windows cannot verify the digital signature for this file.

### ISSUE THREAD

**Issue by gsferopo** [tnodir/fort#9]
I think the installation failed for me on my laptop, if possible I'd prefer not "Disable Driver Signature Enforcement", but do I have no choice?

```
C:\Program Files (x86)\Fort Firewall\driver\scripts>taskkill /F /IM mmc.exe
ERROR: The process "mmc.exe" not found.

C:\Program Files (x86)\Fort Firewall\driver\scripts>sc stop fortfw
[SC] ControlService FAILED 1062:

The service has not been started.


C:\Program Files (x86)\Fort Firewall\driver\scripts>sc delete fortfw
[SC] DeleteService SUCCESS

C:\Program Files (x86)\Fort Firewall\driver\scripts>Del "C:\windows\System32\drivers\fortfw.sys"
End execution... Error Code = 0
        1 file(s) copied.
[SC] CreateService SUCCESS
[SC] StartService FAILED 577:

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

Error: Cannot start the service
End execution... Error Code = 577
Press any key to continue . . .
```

**Comment by tnodir** [comment]
Driver is signed by ordinary code signing certificate, as you can see in its properties.
So it'll not work for Secure Boot, which requires EV certificate.
Please check that you use **Secure Boot**.

To work around it: https://github.com/maharmstone/btrfs#secureboot

**Comment by gsferopo** [comment]
I see thank you, I'll have a look and try now

**Comment by gsferopo** [comment]
I won't be able to try this sorry, I can't access my bias as well since this is my work laptop, I really like this program but I guess I'll just have to try find an alternative, thank you for the help

**Comment by tnodir** [comment]
Have you tried the following from the link?
> "To work around this, go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy in Regedit, create a new DWORD value called UpgradedSystem and set to 1, and reboot."

**Comment by gsferopo** [comment]
I can't change registry values on my laptop, not enough permissions😖

**Comment by tnodir** [comment]
If you can log in as Administrator, then why can't you change registry values.

https://www.howtogeek.com/howto/16909/how-to-disable-access-to-the-registry-in-windows-7/

**Comment by gsferopo** [comment]
I'm too sure, I think the laptop has some changes because its a business machine, I'm admin but the account is still restricted by the System which the company configured before giving me the laptop

And honestly I also don't want to override too many settings since this isnt my laptop, I would definitely get into trouble if something broke 😂

**Comment by tnodir** [comment]
Please try v3.4.2, drivers signed with MS now.
