### ISSUE TITLE
Add a search bar to the Programs window

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#90]
Please add a search bar to the Programs window to make it easier to find applications.

**Comment by tnodir** [comment]
@dashke Can you please describe how the search should work?

E.g. we have following program:
- Path: "C:\Test\abc.exe", Name: "Absolute Beauty Cos"

Questions:
- should a search for "bc" find the "C:\Test\abc.exe"?
- should a search for "est" find the "C:\Test\abc.exe"?
- should a search for "os" find the "Absolute Beauty Cos"?

**Comment by tnodir** [comment]
Implemented in [v3.9.10](https://github.com/tnodir/fort/releases/tag/v3.9.10).
