### ISSUE TITLE
Custom icon not set after system restart

### ISSUE THREAD

**Issue by dashke** [tnodir/fort#92]
1. Set the custom icon in the program folder
2. Restart the application
3. New icon will be used in system tray
4. Restart the system
5. Old icon will appear instead of the custom one

**Comment by tnodir** [comment]
It's because Fort auto-runs with working directory as `C:\Windows\System32`.
Let me fix it by setting the working directory to app's directory on startup...

**Comment by tnodir** [comment]
Thanks, fixed in [v3.9.4](https://github.com/tnodir/fort/releases/tag/v3.9.4).
