### ISSUE TITLE
BSOD Problem 

### ISSUE THREAD

**Issue by kareem007g** [tnodir/fort#94]
hi mr.s tnodir . 
the last thread  i opend  about  BSOD problem was fixed but not for long time . now the  BSOD keep showing up after to many of releases i don't know why this problem  continue to showing up to me ,its become so annoying . now it has different BSOD ERROR :
1-UNEXPECTED KERNEL MODE TRAP  (always show up) 
2-SYSTEM SERVICE ECVEPTION  
3-MEMORY MANGMENT
4- Critical Process Died

this is my specification :
PC:
core i5 gen 6
ram 8g ddr4
OS: windows 10 ghost specter 20h 2 with Reboot Restore Rx program its like deep freeze 
hibernation : on

**Comment by tnodir** [comment]
@kareem007g Please install the [v3.9.5](https://github.com/tnodir/fort/releases/tag/v3.9.5) and send memory minidump from `C:\Windows\Minidump\` to nodir.temir@gmail.com

**Comment by tnodir** [comment]
> i forgot to mention that BSOD UNEXPECTED KERNEL MODE TRAP in gaming

What Fort's options do you use?
Do you use Speed Limiter?

Is that game blocked or allowed?
Can you reproduce the BSOD always?

Please write me in Telegram: https://t.me/nodir_temir

**Comment by kareem007g** [comment]
this is only my setttings 
![Uploading ff setting jpg.jpg…]()

**Comment by tnodir** [comment]
@kareem007g Maybe it's a faulting memory (check with `memtest`)?

**Comment by tnodir** [comment]
@kareem007g Can you please reproduce the BSOD?

Please send a crash minidump from `C:\Windows\Minidump\` to nodir.temir@gmail.com

**Comment by tnodir** [comment]
@kareem007g Try to double check with new RAM.

See ["Debugging a Bit-Flip Error"](https://sillycross.github.io/2023/06/11/2023-06-11/).

**Comment by tnodir** [comment]
@kareem007g Please reopen this issue after BSOD reproducing.
