### ISSUE TITLE
[i18n] Some problems with Chinese translation

### ISSUE THREAD

**Issue by Initial-heart-1** [tnodir/fort#97]
Hi. I noticed that this project uses Crowdin for i18n. When I checked the translation, I noticed a lot of machine translation. This did not make for a good experience.
Is it possible to revise the translation? If so, I can help (in fact, I have already submitted some of the corrections on Crowdin).

**Comment by tnodir** [comment]
Hi, feel free to use Crowdin for translations.
Thanks.
